更新gm包和Tidyverse优雅编程两篇文章
cosname/cosx.org pull request #1003
Opened 2021-12-12 11:10 UTC by EldenBob

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2021-12-14 15:23 UTC, yufree commented
额，以后最好一篇文章一个PR。另外这两篇应该是会议演讲改的，是否需要审稿，请 @yihui @XiangyunHuang 来定。

2021-12-14 15:36 UTC, yihui commented
是的，以后请尽量用 git 分支来提交 PR，一篇文章一个分支，一个分支一个 PR。

除此之外我没什么大的意见。gm 文中的音乐文件可否单独上传后使用链接（可用 cosname/uploads 库），而不是 base64 编码？

2021-12-15 01:01 UTC, XiangyunHuang commented on content/post/2021-12-12-Tidyverse-Elegant-programming.md
> +  - 推荐文章
分类改为 R 语言

2021-12-15 01:01 UTC, XiangyunHuang commented on content/post/2021-12-12-Tidyverse-Elegant-programming.md
> +  -
标签，添加 tidyverse

2021-12-15 01:02 UTC, XiangyunHuang commented on content/post/2021-12-12-Tidyverse-Elegant-programming.md
> +slug:
slug 添加 elegant-tidyverse

2021-12-15 01:02 UTC, XiangyunHuang commented on content/post/2021-12-12-Tidyverse-Elegant-programming.md
> +forum_id:
@Perfectizer 麻烦林峰添加论坛 ID

2021-12-15 01:03 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +  -
分类改为 R 语言

2021-12-15 01:03 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +tags:
标签添加 「gm」 和「音乐制作」两个

2021-12-15 01:04 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +slug:
slug 改为 make-music-with-gm

2021-12-15 01:04 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +forum_id:
麻烦 @Perfectizer 添加论坛 ID

2021-12-15 01:06 UTC, XiangyunHuang requested changes
YAML 内容上请稍作补充，内容上没有更多补充，按益辉的意见改一下吧。

2022-01-07 15:15 UTC, yufree commented
额，怎么又多了yaml信息不全的一篇文章？请补全yaml分类信息与审稿信息，谢谢！

2022-01-07 17:55 UTC, yihui commented
因为没有建 git 分支，所有向 master 分支推送的内容都会继续出现在这个 PR 里。这也是为什么最早的时候我说一篇文章建一个新分支，不过这个事情对新手来说理解起来可能有点困难，而且要搞清楚分支之间的依从关系，画张图就明白了。

2022-04-10 12:50 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +  -
目前成立了各个栏目，所以分类可以按栏目走，改为「软件工具」

2022-04-10 12:53 UTC, XiangyunHuang commented
今天例会上讨论后，王老师 @xiaoningwang  那边后续会安排一位同学专门负责主站文章的编辑。

2022-04-10 12:57 UTC, XiangyunHuang commented
两篇文章都在微信端已经发过了，除了一些格式，我没有对内容修改，应该不需要走审稿了，麻烦 @yufree 抽空合并一下。

2022-04-10 12:59 UTC, XiangyunHuang commented on content/post/2021-12-12-Tidyverse-Elegant-programming.md
> +forum_id:
我先越俎代庖加了

2022-04-10 12:59 UTC, XiangyunHuang commented on content/post/2021-12-07-gm-package.md
> +forum_id:
已经加了

2022-04-10 14:39 UTC, yufree approved these changes

2022-04-10 14:40 UTC, XiangyunHuang approved these changes
done

2022-04-10 14:40 UTC, merged