2022-04-29-history
cosname/cosx.org pull request #1032
Opened 2022-04-29 14:54 UTC by SHL12

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [x] 主编审核确认接收
  - [x] 主编安排审稿人
  - [x] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [x] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [x] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2022-05-01 13:50 UTC, yufree requested changes

2022-05-01 13:50 UTC, yufree commented on content/post/2022-04-29-history.md
> +#西南联大时期的许宝騄与戴世光
`#` 后要有空格，否则不被解析为标题，通篇需要修改

2022-05-01 13:50 UTC, yufree commented on content/post/2022-04-29-history.md
> +!(https://github.com/SHL12/statictics/blob/main/1.jpg?raw=true) (中国概率论与数理统计研究的开拓者之一)
链接格式不对 应使用这样的格式 `![图片说明](链接)`

2022-05-01 13:50 UTC, yufree commented on content/post/2022-04-29-history.md
> +slug: history
这个slug其实可以指向性强一些

2022-05-01 13:50 UTC, yufree commented on content/post/2022-04-29-history.md
> +许宝騄(1910－1970)与戴世光(1908－1999)是我国近现代统计学界的两面旗帜。许宝騄是中国数学家、统计学家，北京大学一级教授。1928年入燕京大学学习化学，1930年转入清华大学攻读数学，毕业后在北京大学数学系任助教。1936年赴英留学，在伦敦大学、剑桥大学学习，1938年获哲学博士学位，1940年又获科学博士学位。同年回国，任北京大学教授，执教于昆明西南联合大学。1945年再次出国
参考文献可以用脚注形式，可以参考[这里](https://bookdown.org/yihui/blogdown/output-format.html)，用`...统计宗师[^1]`，然后参考文献那边可以写成 `[^1]: 许宝騄先生纪念文集编委会．道德文章垂范人间，纪念许宝騄先生百年诞辰［M］．北京: 北京大学出版社，2010. ` 当然如果文献过多，可以考虑用bib文件。

2022-05-01 13:50 UTC, yufree commented on content/post/2022-04-29-history.md
> +##作者简介
主站已经有袁老师个人信息，所以应删掉这部分

2022-05-04 17:47 UTC, SHL12 commented
老师好，修改完了，但是那个参考书籍不太确定是不是那样弄

2022-05-05 12:19 UTC, yufree requested changes

2022-05-05 12:19 UTC, yufree commented on content/post/2022-04-29-history.md
> +---
这里参照之前文章加上你的名字作为编辑

2022-05-05 13:07 UTC, SHL12 commented
已修改

2022-05-08 01:39 UTC, yufree requested changes

2022-05-08 01:39 UTC, yufree commented on content/post/2022-04-29-history.md
> +从1941年到1945年夏许宝騄在西南联大开过“微积分”、“微分几何”、“近世代数”、“富里哀级数与积分”等课程，特别是首次在我国高校中开设了“数理统计”课程。当时的学生钟开莱(Kai- Lai Zhong，美国斯坦福大学教授)回忆说: “他开了一门很长的课程，从测度和积分开始，讲到概率论，再通向数理统计。课程的第一部分基于Carathéodory Vorlesungenüberreelle F
```suggestion
从1941年到1945年夏许宝騄在西南联大开过“微积分”、“微分几何”、“近世代数”、“富里哀级数与积分”等课程，特别是首次在我国高校中开设了“数理统计”课程。当时的学生钟开莱(Kai- Lai Zhong，美国斯坦福大学教授)回忆说: “他开了一门很长的课程，从测度和积分开始，讲到概率论，再通向数理统计。课程的第一部分基于Carathéodory Vorlesungenüberreelle Funktionen，第二部分则取材于Cramer的Ｒandom Variables and Probability Distributions。他是一个风度优雅而又富有激情的老师，随身带着预先写在本子上的完整的备课笔记。他喜欢在课堂上点出微妙之处。例如，在推导特征函数的反演公式的时候，他强调Lebesgue-Stieltjes积分是能在单个点上积分的。” [^1]

```

2022-05-08 01:39 UTC, yufree commented on content/post/2022-04-29-history.md
> +关于国情普查研究所的工作，陈达在《浪迹十年之联大琐记》有较细致的记载(陈达，2013)［6］。“民国二十七年(1938年)，余于离蒙自① 前一个月，接清华聘书一件，聘余为国情普查研究所所长，学校决定以预算的一部设立五研究所，内四所与自然科学有关:即:(一)属，(二)无线电，(三)航空，(四)农业，其第五所与社会科学有关，特别注重人口，经费每年四万元，七月末旬戴世光君自欧洲归国，已由学校聘为本所职
```suggestion
关于国情普查研究所的工作，陈达在《浪迹十年之联大琐记》有较细致的记载［^6］。“民国二十七年(1938年)，余于离蒙自① 前一个月，接清华聘书一件，聘余为国情普查研究所所长，学校决定以预算的一部设立五研究所，内四所与自然科学有关:即:(一)属，(二)无线电，(三)航空，(四)农业，其第五所与社会科学有关，特别注重人口，经费每年四万元，七月末旬戴世光君自欧洲归国，已由学校聘为本所职员，到蒙自时关于研究有所商谈。余拟选一试验区，作小规模的人口普查，请戴君协助。戴君前在清华经济系毕业，考得游美公费，专修统计学，注重人口统计。同时请李景汉兄指导，特别关于调查方面。

```

2022-05-08 01:39 UTC, yufree commented on content/post/2022-04-29-history.md
> +清华国情普查研究所设在呈贡县的文庙，呈贡位于昆明市东南郊区，距昆明市区约 30 公里。当时住在文庙的戴世光要到城里给学生上课，经常和吴泽霖等教授一起徒步十里到呈贡火车站，然后搭 乘滇越铁路火车到昆明，住在西南联大教师宿舍集中上两天课再返回呈贡。中国人民大学教授、西南联大毕业生林富德回忆戴世光时说: “我和戴老师有很多年接触。1938 年他回来后在清华教书，当时他住在昆明郊区，除了上课以外不大进城
```suggestion
清华国情普查研究所设在呈贡县的文庙，呈贡位于昆明市东南郊区，距昆明市区约 30 公里。当时住在文庙的戴世光要到城里给学生上课，经常和吴泽霖等教授一起徒步十里到呈贡火车站，然后搭 乘滇越铁路火车到昆明，住在西南联大教师宿舍集中上两天课再返回呈贡。中国人民大学教授、西南联大毕业生林富德回忆戴世光时说: “我和戴老师有很多年接触。1938 年他回来后在清华教书，当时他住在昆明郊区，除了上课以外不大进城。在昆明时我没有上过他的课，但我知道有这么一位年轻老师。怎么知道的呢? 戴老师上课很开放，他在介绍自己姓名时，自称 “Put the world’s light on my head”，这样学生都很接受他。当时的课堂很注意课堂气氛，启发学生。”[^2]

```

2022-05-08 07:58 UTC, SHL12 commented
已修改

2022-05-09 14:07 UTC, yufree commented on content/post/2022-04-29-history.md
> +西南联大的教授们生活固然艰苦，但他们豁达、乐观，经常聚在一起，文娱体育活动丰富。许宝騄先生在联大教授中因昆曲而出名。余斌《西南联大－昆明记忆》第三册“文化与生活”有这么一篇 “浦江清戏咏 一去二三里 …”[^5]。“西南联大的教授和夫人中，喜好戏曲及传统音乐的不乏其人。1941年夏，老舍应联大中文系邀请来讲学，下榻青云街靛花巷，那里是联大教授宿舍，里面就住着好几位昆曲专家和爱好者。水平最高的要数
`而且要彩唱 ! `这里多了个空格，可以用 ctrl/cmd + F 找下所有空格，看是不是有问题

2022-05-09 14:38 UTC, SHL12 commented
空格已修改。
公众号里的① 在文中不是引文也没有特殊含义，已删掉。

2022-05-09 16:52 UTC, yufree commented on content/post/2022-04-29-history.md
> +meta_extra: "编辑：刘姝含"
此处可以用论坛管理员ID生成一个帖子，然后把帖子URL的编号放过来就可以合并了

2022-05-09 16:54 UTC, SHL12 commented
已修改

2022-05-09 17:05 UTC, SHL12 commented
加上了帖子URL的编号

2022-05-10 14:19 UTC, merged