投稿：北美博士项目申请攻略 张沥今
cosname/cosx.org pull request #1068
Opened 2022-09-30 06:02 UTC by zhanglj37

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改
  - [ ] 已发其他公众号的文章，请在投稿前注明相关公众号信息，并建议给统计之都公众号开白名单

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。  
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章，转交微信端编辑（项目管理中标注PR编号跟进）
  - [ ] 微信编辑、发布，~~阅读原文附主站链接~~，文末附作者介绍 

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2022-10-03 04:38 UTC, XiangyunHuang requested changes

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +slug: tutorial-on-phd-application
这里加一个文章分类，推荐文章

```
categories:
  - 推荐文章
```

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +<a name="material"></a>
这个是用来做什么的？ `<a name="material"></a>`

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +[Bioengineering方向申请经验]( https://www.1point3acres.com/bbs/thread-532556-1-1.html)
建议使用无序列表

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +先简单介绍流程。申请必需的环节为：择校、网申和可能的面试。必需的材料通常包括：简历、三封推荐信、成绩单、和申请文书。此外有些项目需要GRE，如果自己不符合英语考试豁免人群（一般包括已经在国外学习两年及以上并获得或即将获得学位的人），通常还需要语言考试（如，TOEFL）。有些项目会有额外的要求，比如成绩单要认证，或者需要Diversity statement等等。
Diversity statement 建议保留英文的同时给一个中文翻译

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +[强committee CS PhD项目审材料经验1](https://www.1point3acres.com/bbs/thread-585851-1-1.html)（部分内容需要积分才能看，在论坛内签到可以获得积分），[经验2]( https://www.1point3acres.com/bbs/thread-463109-1-1.html)
强committee 是什么意思？

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +[UC SD 审核流程](https://www.youtube.com/watch?v=5KtmOlEIdTk)：从招生视角看网申材料
UC SD 是什么意思？

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +申请是一个非常全面的考虑，**优势永远可以弥补劣势**。标化考试如GRE TOEFL的影响没有那么大，过一定标准即可。如果哪一项不好那么其他的优势背景也可以弥补。几份申请必备材料的重要性通常是：CV (中的研究经验) + 研究相关推荐信 > > GPA > GRE > TOEFL。文书（通常是statement of purpose）的排序因项目和老师而异。
CV 可以改为简历，GPA、GRE、TOEFL 、statement of purpose 可以附带中文翻译

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +所有的材料主要为两个方面服务：1）表达对某个研究方向的好奇、动机、热爱（文书、研究经验）。2）能够在某个研究方向工作的能力/潜力（研究经验、推荐信）。
建议改为

所有的材料主要为两个方面服务：其一是表达对某个研究方向的好奇、动机、热爱（文书、研究经验），其二是能够在某个研究方向工作的能力/潜力（研究经验、推荐信）。

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +建议找找同领域的博士生和教授们的简历参考，GitHub库里放了我参考的一部分简历的链接。大家可以从这些简历中自己总结1）需要有哪些模块哪些具体信息；2）怎么表达自己在项目中的贡献；3）学术领域看重哪些技能和经历；4）排版。但是申请者的简历和这些博士生/教授的简历有几点不同：1）需要简述每段实习中做了什么，有细节来突出技能；2）可以放上没有发表成果但是能够凸显能力的研究经历，比如可以放课程项目。
用一些有序列表更加清晰些。

2022-10-03 04:38 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +建议同时做一个个人网站（统计之都主站有非常多攻略介绍如何建立个人网站）放简历：1) 可以实时更新自己的简历信息；2) 可以用visit tracker记录访问，辅助了解对方是否看到了邮件/开始审核材料；3) 有些老师更喜欢直接看网站而不是下载简历； 4) 也可以说明自己爱折腾、自我驱动。
visit tracker 可以给个超链接，同时翻译一下。

2022-10-04 16:22 UTC, zhanglj37 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +slug: tutorial-on-phd-application
已增加

2022-10-04 16:23 UTC, zhanglj37 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +<a name="material"></a>
已删除

2022-10-04 16:23 UTC, zhanglj37 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +[Bioengineering方向申请经验]( https://www.1point3acres.com/bbs/thread-532556-1-1.html)
已修改

2022-10-04 16:23 UTC, zhanglj37 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +先简单介绍流程。申请必需的环节为：择校、网申和可能的面试。必需的材料通常包括：简历、三封推荐信、成绩单、和申请文书。此外有些项目需要GRE，如果自己不符合英语考试豁免人群（一般包括已经在国外学习两年及以上并获得或即将获得学位的人），通常还需要语言考试（如，TOEFL）。有些项目会有额外的要求，比如成绩单要认证，或者需要Diversity statement等等。
已修改-多样性陈述文书（Diversity Statement）

2022-10-20 14:09 UTC, MelodyRen1998 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +项目官方联系邮箱：每个项目都会注明有问题可以寻找的小蜜，不懂的问就行了。比如文书要求，送分，这些申请细节都能得到答案。
前文写过小秘，这两个词用一个就可以了

2022-10-20 14:09 UTC, MelodyRen1998 commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +（2）匹配极其重要。博士申请中量化指标很难起到决定性的效果，会比较看重学生背景和追求与项目/某个实验室是否匹配，是否是个适合在此工作的人。这种适合包括研究方向、未来计划、甚至性格。强背景的人也可能因为不适合被拒，因而没有必要盯着GT GPA文章数量去判断自己录取的概率。
GT、GPA、文章数量 中间少了标点符号

2022-10-22 23:41 UTC, zhanglj37 commented
感谢 @MelodyRen1998 非常细致的建议！已逐条进行修改。

2022-10-28 05:54 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +date: '2022-09-29'
更新日期

```suggestion
date: '2022-10-28'
```

2022-10-28 05:59 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +---
```suggestion
forum_id: 423627
---
```

2022-10-28 05:59 UTC, XiangyunHuang commented on content/post/2022-09-29-tutorial-on-phd-application.md
> +---
我开贴加了论坛 ID

2022-10-28 06:06 UTC, XiangyunHuang approved these changes
谢谢沥今 @zhanglj37 和怡萌 @MelodyRen1998 ，审稿修改结束了。文章会先在主站发出，后续还得辛苦一下 @zhanglj37 帮忙请公众号「荷兰心理统计联盟」给统计之都公众号开白名单，之后就进入微信端编辑了。

2022-10-28 06:06 UTC, merged

2022-10-28 06:20 UTC, zhanglj37 commented
好的，感谢师兄和怡萌的审稿，白名单已开～