统计之都访谈第46期：数据科学先驱John Tukey
cosname/cosx.org pull request #1082
Opened 2022-12-15 17:33 UTC by robinchan524

create Turkey-CN.md

2023-01-01 18:15 UTC, yufree requested changes

2023-01-13 16:17 UTC, robinchan524 commented on content/post/Turkey-CN.md
> +title: "统计之都访谈第46期：数据科学先驱John Tukey"
[2023-01-14-cos-restructured.md](https://github.com/cosname/cosx.org/files/10413346/2023-01-14-cos-restructured.md)

2023-01-13 16:26 UTC, robinchan524 commented on content/post/Turkey-CN.md
> +title: "统计之都访谈第46期：数据科学先驱John Tukey"
[2022-12-05-cos-restructured.md](https://github.com/cosname/cosx.org/files/10413412/2022-12-05-cos-restructured.md)

2023-01-13 17:13 UTC, yufree commented on content/post/Turkey-CN.md
> +title: "统计之都访谈第46期：数据科学先驱John Tukey"
请直接修改PR的文件名，否则依然无法看到预览

2023-01-30 02:28 UTC, yihui commented on content/post/2023-1-30-Turkey-CN.md
> +slug: interview-of-john-turkey
是 Tukey，不是火鸡（文件名也有同样的错误）。

```suggestion
slug: interview-of-john-tukey
```

2023-02-12 03:43 UTC, yufree approved these changes

2023-02-12 18:37 UTC, merged