fix #662: 使用方向键翻页
cosname/cosx.org pull request #1118
Opened 2023-11-13 15:10 UTC by CyrusYip

2023-11-13 15:22 UTC, yihui requested changes
谢谢，这代码我以前已经写过了，可以直接用。

2023-11-13 15:22 UTC, yihui commented on layouts/partials/head_custom.html
> +<script async src="{{ relURL "/js/shortcuts.js" }}"></script>
```suggestion
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils/js/post-nav.min.js" defer></script>
```

2023-11-13 15:54 UTC, CyrusYip commented on layouts/partials/head_custom.html
> +<script async src="{{ relURL "/js/shortcuts.js" }}"></script>
我这个比你的功能多一些。除了文章翻页，首页也能翻页，还添加了提示框。没提示框估计读者也不知道能翻页。

2023-11-17 17:08 UTC, CyrusYip commented on layouts/partials/head_custom.html
> +<script async src="{{ relURL "/js/shortcuts.js" }}"></script>
可是不同 Hugo 主题里面那些元素的类名不一样，咋办？

2023-11-17 18:38 UTC, CyrusYip commented on static/js/shortcuts.js
> +  });
`tabindex` 应该加到主题，此处代码只是临时使用。

2023-11-17 18:47 UTC, CyrusYip commented on layouts/partials/head_custom.html
> +<script async src="{{ relURL "/js/shortcuts.js" }}"></script>
@yihui 我已经把你代码抄得差不多了，应该没问题了。

https://github.com/yihui/misc.js/blob/83b2aea9132d522ff8260df6df8ebdc874fad62d/js/post-nav.js#L15-L21

就是这段没看明白在干啥。

2024-04-14 15:52 UTC, yihui approved these changes
不好意思，放这儿太久放忘了。

2024-04-14 15:53 UTC, merged