投稿:用shiny和echarts4r制作一个COVID-19的dashboard 苏玮
cosname/cosx.org pull request #907
Opened 2020-09-01 12:04 UTC by swsoyee

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2020-09-01 13:15 UTC, yufree commented
感谢投稿，不知轩哥 @yixuan 有时间看下吗？

2020-09-07 17:37 UTC, yufree commented
湘云有空看下这篇吗？@XiangyunHuang

2020-09-08 02:31 UTC, XiangyunHuang commented
@yufree 好的👌，这周末我会审一下

2020-09-11 08:07 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +forum_id: InfinityLoop
论坛 ID forum_id 就用帖子 https://d.cosx.org/d/421731-covid-19dashboard 对应的  ID 怎么样？@Perfectizer 
论坛 ID 和帖子链接的对应关系就是前面这一串数字，比如这里的 421731

2020-09-11 08:11 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +本文主要分享一下我从1月底开始的一个用`shiny`制作的用来关注日本疫情动态的项目。项目本身为日文版`(https://covid-2019.live/)`，然后5月份左右开始逐步翻译成中`(/cn)`英文`(/en)`版本。项目所有代码和数据集全部开源[swsoyee/2019-ncov-japan](https://github.com/swsoyee/2019-ncov-japan)。只
shiny 之类的 R 包名称可以统一加粗 **shiny**，链接可以用一对尖括号包住 <https://covid-2019.live/>

英文类的字词，比如 Clone 可以汉化为克隆， commit 可以汉化为提交， dashboard 可以汉化为仪表盘，除了专有名词（比如 Github）外，建议尽量少中文英文混杂，下同

2020-09-11 08:16 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +需要注意的是由于项目开发是本人利用工作之余时间赶制而成，我本人也不是R语言老手和shiny应用开发老手，代码质量和项目结构可能极其恐怖（能用就行），各位吐槽时希望能嘴下留情。如果大家能帮忙提出改进的PR当然是最好的了！
作者大可不必这么谦虚，这么谦虚的话，我都要无地自容了。我相信大部分人第一眼看到的时候还是很惊艳的，会很想知道作者是怎么做到的，将想法变成一款数据产品。

2020-09-11 08:23 UTC, XiangyunHuang requested changes
总体上，作为一款 shiny 打造的数据产品，给人眼前一亮的视觉冲击是本文最显著的特色！其次，对于想要掌握背后技术的人，相信会毫不犹豫地去看作者的源码仓库。

2020-09-11 08:24 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +![Figure1](https://raw.githubusercontent.com/swsoyee/2019-ncov-japan/doc/www/doc/img/Figure1.png)
文字和图之间需要空行，这样更加美观，作者不妨看看预览效果 https://deploy-preview-907--cosx.netlify.app/2020/09/covid19-bulletin-board/

2020-09-11 09:23 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +**下面主要是一些详细的个人思考流程，废话比较多不感兴趣的各位可以直接跳过。**
本段和下面那段**都不是**废话，很体现数据思维，甚至可以说是商业思维。数据收集、组织、管理是打造数据产品的基石，数据源头的可靠性、收集的规范性、组织的科学性、管理的合理性直接决定数据产品的开发效率以及应用价值

2020-09-11 09:24 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +可能对于一些老手来说下面的这些可能是初级问题，但由于非应用开发专业的前生信专业的渣渣的我来说也走过这个坑，作为经验还是想分享给大家，应用开发老手可以直接跳过。简单来说：
不管读者是高级用户还是初级用户，建议全把他们当作小白来介绍。

2020-09-11 09:37 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +在很多疫情dashboard中，通常采用地图的形式展示每个地区的确诊人数情况（可用`leaflet`实现），但每个国家的所发表的确诊患者的详细程度不同，比如国内包括香港的dashboard可以实现精确到小区和楼栋，而日本通常最细只能获取到区级范围的信息，如果使用地图来展现的化，坐标定位就会是一个很大的问题，因此在这里我使用了矩形树图来进行可视化。
处处体现了作者数据驱动的思维，选择合适的图形来展示数据并不是人人都具备的能力

2020-09-11 09:47 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +接下来是PCR检测人数、康复和新冠咨询热线的接线情况等。在`echarts4r`下支持图例点击（显示/隐藏）效果，而在切换的过程中会有**默认过渡动画**效果，个人认为这一点比`plotly`更为出色。
建议在整个项目的技术实现过程中积累起来的宝贵经验单独开辟一节的篇幅介绍。建议正文主要以图文并茂的方式陈述功能、内容、想法和创意，借助数据思维给大家讲一个故事。

2020-09-11 10:16 UTC, XiangyunHuang commented
另外，有一个问题就是 **shinydashboardPlus** 包的函数 `descriptionBlock()` 的参数非兼容性变化，比如 `number_color` 要变成 numberColor 等，详见
https://github.com/RinteRface/shinydashboardPlus/blob/master/NEWS.md

后来，也注意到作者 @swsoyee 已经在处理这个[问题](https://github.com/swsoyee/2019-ncov-japan/pull/2624)了，是否有可能在文章正式发出前修复这个问题?

2020-09-11 10:28 UTC, XiangyunHuang commented
关于文章标题，我觉得作者不妨再斟酌一下，目前标题有些平淡，内容实则非常硬核，我先抛个砖，比如 **如何打造访问量高达 1300+ 万的企业级 shiny 应用**

@yihui @yufree 不妨也来围观一下

2020-09-11 11:13 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +右侧为一个关于确诊患者去向的Sankey图。用于显示每日确诊患者的流向（症状的有无轻重、是否在住院、出院和死亡等信息）。但由于厚生劳动省所发表的数据格式有过多次变更，而上述信息已经不再进行详细公布，因此这个Sankey图可以说已经可有可无了。待以后有时间再进行修正。
Sankey图可以改为桑基图

2020-09-11 11:16 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +在全国数据总览的`box`中的底部，使用`shinydashboardPlus`的`DescriptionBlock`制作了一排用于展示主要数据的底栏。一开始出于全面展示日本境内的疫情状况（包括医疗资源应对等）的目的，同时将公主号游轮的数据纳入了统计范围当中了（根据WHO的标准，公主号游轮单独进行了统计而不并作日本的数据）。因此在这里为了说明这一情况，把日本国内的计数和游轮进行分开统计以免造成误
- 建议全文 R 包都加粗表示，比如 **shinydashboardPlus**
- 建议 R 函数都用一对反引号包裹，且加一对英文小括号 ()，比如 `DescriptionBlock()`

2020-09-11 13:16 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +在全国数据总览的`box`中的底部，使用`shinydashboardPlus`的`DescriptionBlock`制作了一排用于展示主要数据的底栏。一开始出于全面展示日本境内的疫情状况（包括医疗资源应对等）的目的，同时将公主号游轮的数据纳入了统计范围当中了（根据WHO的标准，公主号游轮单独进行了统计而不并作日本的数据）。因此在这里为了说明这一情况，把日本国内的计数和游轮进行分开统计以免造成误
Fixed in e0f103b

2020-09-11 13:16 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +右侧为一个关于确诊患者去向的Sankey图。用于显示每日确诊患者的流向（症状的有无轻重、是否在住院、出院和死亡等信息）。但由于厚生劳动省所发表的数据格式有过多次变更，而上述信息已经不再进行详细公布，因此这个Sankey图可以说已经可有可无了。待以后有时间再进行修正。
Fixed in 8459a69

2020-09-11 13:17 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +![Figure1](https://raw.githubusercontent.com/swsoyee/2019-ncov-japan/doc/www/doc/img/Figure1.png)
Fixed in 68ca7df

2020-09-11 13:17 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +forum_id: InfinityLoop
Fixed in 68ca7df

2020-09-11 14:39 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +本文主要分享一下我从1月底开始的一个用`shiny`制作的用来关注日本疫情动态的项目。项目本身为日文版`(https://covid-2019.live/)`，然后5月份左右开始逐步翻译成中`(/cn)`英文`(/en)`版本。项目所有代码和数据集全部开源[swsoyee/2019-ncov-japan](https://github.com/swsoyee/2019-ncov-japan)。只
Fixed in 3a27054 2b9b6f6

2020-09-11 14:40 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +需要注意的是由于项目开发是本人利用工作之余时间赶制而成，我本人也不是R语言老手和shiny应用开发老手，代码质量和项目结构可能极其恐怖（能用就行），各位吐槽时希望能嘴下留情。如果大家能帮忙提出改进的PR当然是最好的了！
Fixed in 3a27054

2020-09-11 16:34 UTC, swsoyee commented
@XiangyunHuang 感谢黄编辑在百忙之中的细致Review，对于所指出的地方基本都进行了修改了，请查阅。

> 另外，有一个问题就是 **shinydashboardPlus** 包的函数 `descriptionBlock()` 的参数非兼容性变化，比如 `number_color` 要变成 numberColor 等，详见
> https://github.com/RinteRface/shinydashboardPlus/blob/master/NEWS.md
> 
> 后来，也注意到作者 @swsoyee 已经在处理这个[问题](https://github.com/swsoyee/2019-ncov-japan/pull/2624)了，是否有可能在文章正式发出前修复这个问题?

这个问题应该会在这周末内可以修复 https://github.com/swsoyee/2019-ncov-japan/issues/2623#issuecomment-691191053

2020-09-12 02:06 UTC, XiangyunHuang commented
@swsoyee 剩下的是一些语句通顺和措辞，交给编辑部吧，我会先修改一些。之后，安排人在微信端编辑，生成微信公众号文章的预览链接给到您，您觉得没有问题，就正式推送。

2020-09-12 02:51 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +文笔不好请大家多多包涵。正文夹杂了不少冗长的个人对于这个项目的定位以及思考的过程，并进行了引用标注，各位看官可以选择跳着看即可。
审稿人和编辑部的部分职责就是帮助投稿人更好地打磨文字上的内容，所以请不要太担心。

2020-09-12 03:40 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +文笔不好请大家多多包涵。正文夹杂了不少冗长的个人对于这个项目的定位以及思考的过程，并进行了引用标注，各位看官可以选择跳着看即可。
@XiangyunHuang PR内容可以随便修改的没有关系，劳烦编辑了☺️

2020-09-12 04:00 UTC, XiangyunHuang commented
@swsoyee 那请把我加到你的[仓库](https://github.com/swsoyee/cosx.org)中，给编辑修改权限，这样我就可以直接修改 PR 了，目前没有权限推送不了修改


```bash
(r-tensorflow) ➜  cosx.org git:(master) git fetch origin refs/pull/907/head:covid-19  
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 96 (delta 65), reused 65 (delta 49), pack-reused 15
Unpacking objects: 100% (96/96), done.
From https://github.com/cosname/cosx.org
 * [new ref]         refs/pull/907/head -> covid-19
(r-tensorflow) ➜  cosx.org git:(master) git checkout covid-19   
Switched to branch 'covid-19'
(r-tensorflow) ➜  cosx.org git:(covid-19) git remote add swsoyee https://github.com/swsoyee/cosx.org.git  
(r-tensorflow) ➜  cosx.org git:(covid-19) git push --set-upstream swsoyee covid-19 
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.21 KiB | 1.21 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/swsoyee/cosx.org.git
 ! [remote rejected] covid-19 -> covid-19 (permission denied)
error: failed to push some refs to 'https://github.com/swsoyee/cosx.org.git'
```

2020-09-12 04:23 UTC, swsoyee commented
> @swsoyee 那请把我加到你的[仓库](https://github.com/swsoyee/cosx.org)中，给编辑修改权限，这样我就可以直接修改 PR 了，目前没有权限推送不了修改
> 
> 
> 
> 
> 
> ```bash
> 
> (r-tensorflow) ➜  cosx.org git:(master) git fetch origin refs/pull/907/head:covid-19  
> 
> remote: Enumerating objects: 81, done.
> 
> remote: Counting objects: 100% (81/81), done.
> 
> remote: Compressing objects: 100% (32/32), done.
> 
> remote: Total 96 (delta 65), reused 65 (delta 49), pack-reused 15
> 
> Unpacking objects: 100% (96/96), done.
> 
> From https://github.com/cosname/cosx.org
> 
>  * [new ref]         refs/pull/907/head -> covid-19
> 
> (r-tensorflow) ➜  cosx.org git:(master) git checkout covid-19   
> 
> Switched to branch 'covid-19'
> 
> (r-tensorflow) ➜  cosx.org git:(covid-19) git remote add swsoyee https://github.com/swsoyee/cosx.org.git  
> 
> (r-tensorflow) ➜  cosx.org git:(covid-19) git push --set-upstream swsoyee covid-19 
> 
> Enumerating objects: 9, done.
> 
> Counting objects: 100% (9/9), done.
> 
> Delta compression using up to 12 threads
> 
> Compressing objects: 100% (5/5), done.
> 
> Writing objects: 100% (5/5), 1.21 KiB | 1.21 MiB/s, done.
> 
> Total 5 (delta 4), reused 0 (delta 0)
> 
> remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
> 
> To https://github.com/swsoyee/cosx.org.git
> 
>  ! [remote rejected] covid-19 -> covid-19 (permission denied)
> 
> error: failed to push some refs to 'https://github.com/swsoyee/cosx.org.git'
> 
> ```

已经发送邀请了，麻烦您了

2020-09-12 06:10 UTC, swsoyee commented on content/post/2020-09-01-covid19-bulletin-board.md
> +项目开发是利用工作之余的时间，我本人不是R语言和**shiny**应用开发专家，个人精力也有限，项目在功能上已经不会有很大改动了，代码质量和项目结构可能极其恐怖且不规范，能用就行，希望各位读者吐槽之余献言献策，帮助继续维护和迭代项目。
```suggestion
项目开发是利用工作之余的时间，我本人不是R语言和**shiny**应用开发专家，个人精力也有限，项目在功能上已经不会有很大改动了，代码质量和项目结构可能极其恐怖且不规范，能用就行，希望各位读者吐槽之余建言献策，帮助继续维护或推广宣传项目。
```
修改了一个词语（建言献策），精力有限估计应该不会迭代了，所以稍作调整了一下。

2020-09-12 08:30 UTC, XiangyunHuang approved these changes
@yufree 我这没有问题了。

2020-09-12 08:30 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +项目开发是利用工作之余的时间，我本人不是R语言和**shiny**应用开发专家，个人精力也有限，项目在功能上已经不会有很大改动了，代码质量和项目结构可能极其恐怖且不规范，能用就行，希望各位读者吐槽之余献言献策，帮助继续维护和迭代项目。
好的，已经修改

2020-09-12 16:25 UTC, yufree commented
感谢湘云审稿与作者修改，请 @XiangyunHuang 安排微信排版，主站有了回复贴应该可以直接合并 @Perfectizer ，预计下周内发出。

2020-09-13 02:55 UTC, XiangyunHuang commented
@swsoyee 本来是想由编辑来修改主要功能介绍部分，但是考虑到对内容的熟悉程度，还是你来修改比较合适。烦请从以下几个方面修改

1. 语句是否过长
1. 语句之间的停顿词、连接词是否冗余
1. 语句之间的逻辑关系是否合理

具体示例可以参照最新的三次提交记录

2020-09-13 02:57 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +废话了这么多，终于到了主要的仪表盘功能介绍了。代码量较多，这篇文章不着重介绍代码，而仅仅采用流水方式走一遍。
再举个例子

> 废话了这么多，终于到了主要的仪表盘功能介绍了。代码量较多，这篇文章不着重介绍代码，而仅仅采用流水方式走一遍。

还可以改为

>   废话了这么多，终于到仪表盘的功能介绍了。项目本身代码量较大，这篇文章不着重介绍代码，而仅仅采用流水方式走一遍。

2020-09-13 03:01 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +主要以横向布局为主，分为4层结构。
**主要**二字多余

2020-09-13 03:02 UTC, XiangyunHuang commented on content/post/2020-09-01-covid19-bulletin-board.md
> +这部分主要由4个标签构成，其中第一个标签的`疫情地图`由左侧地图右侧表格的结构构成，为整个应用中最为重要的部分。
结构二字多余

2020-09-13 14:28 UTC, swsoyee commented
<summary>借地传图</summary>
<details>

<img width="1624" alt="スクリーンショット 2020-09-13 23 25 41" src="https://user-images.githubusercontent.com/20528423/93020556-b97f5800-f618-11ea-988a-42c2ee46cfe1.png">
<img width="625" alt="図1" src="https://user-images.githubusercontent.com/20528423/93020561-bbe1b200-f618-11ea-81e6-1d24af7dd6a9.png">

</details>

2020-09-13 16:33 UTC, swsoyee commented
@XiangyunHuang 感谢黄编辑，我已润色完毕，shinydashboardPlus的版本升级不兼容问题也已经解决。

2020-09-14 00:32 UTC, XiangyunHuang commented
@swsoyee 太好了！我去安排人编辑一下微信端

2020-09-14 00:39 UTC, XiangyunHuang commented
@swsoyee 愿意提供个人介绍吗？我们会在主站和微信端的文末介绍，具体话术类似我们网站的[成员页面](https://cosx.org/members/)，非常灵活

2020-09-14 00:40 UTC, swsoyee commented
> @swsoyee 愿意提供个人介绍吗？我们会在主站和微信端的文末介绍，具体话术类似我们网站的[成员页面](https://cosx.org/members/)，非常灵活

好的，我稍微想想然后在这里留言？

2020-09-14 00:44 UTC, XiangyunHuang commented
@swsoyee 可以直接提交PR修改成员数据文件 <https://github.com/cosname/cosx.org/blob/master/data/members.yaml>， 它是个 YAML 格式，插入的位置根据你的姓名的拼音字母顺序来

2020-09-14 03:11 UTC, XiangyunHuang commented
@swsoyee 微信端已经编辑好了，这是[预览](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA3OF9OdGx4ZTNacWhQQ2lOWjRURHByOW5tbjZ0QkxDckNTUGZERWtRU1phcFhhV0s4bXJ5MWlDTXRnSDE4WW1PV0dDMVBYQ2dGUU1QUTYyX1UwVzRjaVJPV1A1UGxBcFQyRENXMmpkRGoxTDhpd3J1bG1Qb09ZM2F3cjdjcVh6Ul9RYWpHVVJpb2pqRi1oczNXMGE3WU56NmtTTHJHell5cnJ2SXNUNWpBfn4%3D&chksm=3e859ba309f212b5891570d742e4ce9561b3be16d6b1a846c307ef44ecbd8209c6af991d818c&mpshare=1&scene=1&srcid=0914TIJlZCCDsCynf0RmAqxQ&sharer_sharetime=1600052836843&sharer_shareid=a8d6784ce5af159b4e2a98ca7d7947ae#wechat_redirect)

2020-09-14 03:17 UTC, swsoyee commented
@XiangyunHuang 感谢！我也追加添加了自己的个人信息

2020-09-14 03:23 UTC, XiangyunHuang commented
@swsoyee 👍，那我们晚上8点半，正式推送啦！

@Perfectizer 麻烦微博也同步推广一下

2020-09-14 03:28 UTC, XiangyunHuang commented
@yufree 那我先合并到主库了，生成正式主站链接，微博可以下午或晚上都可以发

2020-09-14 03:43 UTC, XiangyunHuang commented
@yihui @yufree 今天，我和编辑在微信端编辑文章的时候，发现文章中的图片挺多，都是以 Github 作为图床，国内，比如人大校园访问就会出现问题。

@yixuan  我们是不是该刷一波文章的图片，复制一份存到自己的库里了。今后是否可以设置一个定时任务自动化这个过程

2020-09-14 10:06 UTC, merged

2020-09-14 12:52 UTC, XiangyunHuang commented
@swsoyee @yufree 因为这篇文章已经在其它微信公众号平台发布过，现在不是原创了，微信后台只允许转发了。

2020-09-14 12:55 UTC, swsoyee commented
@XiangyunHuang 居然有这种事……这个版本明明更新的😭正文也修改了这么多，不好意思给大家添麻烦了……

2020-09-14 12:57 UTC, XiangyunHuang commented
@swsoyee 微信后台检测相似度很高，不能以原创文章发出来

2020-09-14 14:16 UTC, yufree commented
印象中微信转载时可以做一定修改吧？是不是要开白名单之类，以后已经微信原创的文章再投主站应加上白名单放行的要求。

2020-09-15 02:51 UTC, XiangyunHuang commented
文章若在其它媒体上发过，应该提前告知我们，这样也可以提前和相关媒体联系获取权限

@swsoyee 你是否可以联系之前发过的公众号，让他们给我们开通微信公众号的白名单，把修订版本发出去。你方便加我的微信号吗？我的是 Sophorae

2020-09-15 03:26 UTC, swsoyee commented
@XiangyunHuang @yufree 非常抱歉给大家添麻烦了。我已经邮件联系之前的公众账号开放白名单看能不能把修订版发出去了。
@XiangyunHuang 已加微信。

> 文章若在其它媒体上发过，应该提前告知我们，这样也可以提前和相关媒体联系获取权限

另：或许是否考虑把这个添加到PR模版中去更方便一下。