投稿: 从另一种视角看R语言的Tidyverse方言 [作]Norm Matloff [译]李嵩
cosname/cosx.org pull request #910
Opened 2020-10-13 03:11 UTC by boltomli

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2020-10-13 04:15 UTC, yihui commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +categories: R语言
```suggestion
categories:
- R语言
```

2020-10-13 14:47 UTC, yufree commented
感谢投稿！@boltomli 这篇因为是翻译，湘云 @XiangyunHuang 来把关吧，之后可直接安排微信编辑。

2020-10-15 00:24 UTC, XiangyunHuang commented
@yufree 我因为最近时间比较紧张，请任焱来

2020-10-15 14:46 UTC, Ryanna-github reviewed
去除此处“全部”更加通顺

2020-10-16 02:18 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +**认知过载是很严重的问题**。Tidyverse 的学生要学习的材料相对多得多，这显然不是好的教育方法。在 [“Tidyverse 诅咒”](https://www.r-bloggers.com/the-tidyverse-curse)一文中，作者提到 *此外* 他还“仅仅”用到了 60 个Tidyverse 函数——60！Tidyverse 的“明星” **dplyr** 包含了 263 个
```suggestion
**认知过载是很严重的问题**。Tidyverse 的学生要学习的材料相对多得多，这显然不是好的教育方法。在[“Tidyverse 诅咒”](https://www.r-bloggers.com/the-tidyverse-curse)一文中，作者提到 *此外* 他还“仅仅”用到了 60 个Tidyverse 函数——60！Tidyverse 的“明星” **dplyr** 包含了 263 个函数。
```

2020-10-16 02:39 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +作为对比，只要用户学会了 base-R （不难），就可以用少数几个简单的操作处理各种情况。古话说得好：“授人以鱼，不如授之以渔。”
```suggestion
作为对比，只要用户学会了 base-R （不难），就可以用少数几个简单的操作处理各种情况。古话说得好：“授人以鱼，不如授人以渔。”
```

2020-10-16 02:39 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +**tapply()** 是在 R 语言里最常使用的函数之一。如下所示，不知出于什么原因，Tidy 倡导者不喜欢这个函数，然而这简直是 R 初学者 最好用的函数。
```suggestion
**tapply()** 是在 R 语言里最常使用的函数之一。如下所示，不知出于什么原因，Tidy 倡导者不喜欢这个函数，然而这简直是 R 初学者最好用的函数。
```

2020-10-16 02:47 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +检索过 **dplyr** 的几百个函数后，我没有找到如何把 Tidy 的输出转换为 **tapply()** 提供的更有信息量的表格样式。假使可以做到，既然没法轻易识别出这样的函数，也正好能体现我上述观点，Tidy 过于臃肿，不适合初学者。
```suggestion
检索过 **dplyr** 的几百个函数后，我没有找到如何把 Tidy 的输出转换为 **tapply()** 提供的更有信息量的表格样式。就算这样的函数存在，其难以被轻易识别也正好能体现我上述观点，Tidy 过于臃肿，不适合初学者。
```

2020-10-16 02:48 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +此外，**tapply()** 的输出还有另一重含义，用户能够察觉没有8-汽缸、4-挡位的汽车，这又是在很多应用中非常有意义的一类信息。
```suggestion
此外，**tapply()** 的输出还有另一重含义，让用户能够察觉没有8-汽缸、4-挡位的汽车也是在很多应用中非常有意义的一类信息。
```

2020-10-16 02:54 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +关于这个话题，一个有趣的讨论见 [Charavarty 和 Keller](https://www-ps.informatik.uni-kiel.de/~mh/reports/fdpe02/papers/paper15.ps.gz)。其实他们支持在 CS 专业的编程绪论课堂中使用 FP，但两位作者的目标和学习 R 的人正好是对立的。作者们列出了三个目标，其中一个是讲授计算机科学理论，一般性的讲授
```suggestion
关于这个话题，一个有趣的讨论见 [Charavarty 和 Keller](https://www-ps.informatik.uni-kiel.de/~mh/reports/fdpe02/papers/paper15.ps.gz)。其实他们支持在 CS 专业的编程绪论课堂中使用 FP，但两位作者的目标和学习 R 的人正好是对立的。作者们列出了三个目标，其中一个是讲授计算机科学理论，一般性的讲授 R 语言对此当然没有什么兴趣，更不要说教没有编写代码经验的人学习 R 语言。他们承认，即使是对 CS 学生来说，FP 的一个关键概念 *递归* 也是“显著的障碍”。
```

2020-10-16 03:05 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +> 当然，不过我原本的推特是讲如何教导新人的。
```suggestion
> 说的没错，但我原本的推特是讲如何教导新人的。
```

2020-10-16 03:06 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +这就是我的观点！**新人应该用循环，而不是purrr**。然而 Tidy 推广者不愿让学生用循环。所以用 Tidy 的教员就得避免给学生用这样的例子，同样的例子用 base-R 的教员就很容易处理。
```suggestion
这就是我的观点！**新人应该用循环，而不是purrr**。然而 Tidy 推广者不愿让学生用循环。所以用 Tidy 的教员就得避免给学生用这样的例子，对于同样的例子，用 base-R 的教员就很容易处理。
```

2020-10-16 03:11 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +换句话说，尽管学生可能会说他们喜欢 Tidy “英语”的方面，其好处却不是实在的。他们可能会更精通 R，**更迅捷**，如果学习 base-R 而不是 Tidy。
```suggestion
换句话说，尽管学生可能会说他们喜欢 Tidy “英语”的方面，其好处却不是实在的。如果学习 base-R 而不是 Tidy，他们可能会更精通 R，学得**更快**，。
```

2020-10-16 03:17 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +正如我前面所说，与成功使用 Tidyverse 指导初学者程序员的教员讨论时，我问他们的学生若仅学习 base-R 则是否没有能力学会。他们承认答案是否定的。事实上，在 Tidyverse 之前，成群的人都在学习 base-R，过去没有任何编程背景。
```suggestion
正如我前面所说，与成功使用 Tidyverse 指导初学者程序员的教员讨论时，我问他们学生是否没有能力只学习 base-R，他们承认答案是否定的。事实上，在 Tidyverse 之前，大量在过去没有任何编程背景的人都在学习 base-R，。
```

2020-10-16 03:19 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 不适当的过度概括。
```suggestion
1. 概括性不充分。
```

这里好像和原文意思有出入？

2020-10-16 05:42 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +这就是我教程的第一课。简单！作为对比，用 Tidy 的群体不许使用 base-R 绘图，而是坚持使用 **ggplot2**（再说一次，其实这并不属于 Tidy，只不过有 Tidy 的倡导者常如此描述）。要想用 Tidy，教员需要如下操作
```suggestion
这就是我教程的第一课。简单！相反，用 Tidy 的群体不使用 base-R 而坚持使用 **ggplot2**绘图（再说一次，其实这并不属于 Tidy，只不过有 Tidy 的倡导者常如此描述）。要想用 Tidy，教员需要如下操作
```

2020-10-16 05:45 UTC, Ryanna-github reviewed
和原文进行对比后，已修改文章一些翻译句式和符号的问题~

2020-10-18 03:16 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +- R
分类 R 语言了，这里关键词可以改为 Base R

2020-10-18 03:18 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +title: '从另一种视角看 R 语言的 Tidyverse“方言” '
从另一个视角看 R 语言的方言 Tidyverse

2020-10-18 03:20 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +## Norm Matloff, Prof. of Computer Science, UC Davis (former Prof. of Statistics at UCD)
除了作者名字，这里还是可以翻译一下的

2020-10-18 03:24 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +Tidyverse 包中另一个特殊的库，面向 *函数式编程*（FP）的 **purrr**，有 177 个函数。关于复杂性的论点依然适用；我们再次遇到和上述 **dplyr** 同样的问题，“有太多函数要学”。
FP 建议同时补全，括号里为（Functional Programming，简称 FP）

2020-10-18 03:28 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +真有什么区别吗？初学者即使没有编程背景，看过一些例子后，也无法快速采用这两者中的任一种吗？声称 **dplyr** 具有高度可教学性的教员也会欣然同意他们的学生可以容易地学会 **data.table**，只要给一些例子，也就是我为初学者所选择的 base-R。
全文中的教员都改为老师应该更自然一些

2020-10-18 03:33 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +* RStudio 提倡 Tidyverse 的时候声称它能够使非程序员更容易学习 R。出于上述原因，与之正相反，**我要提出异议：Tidyverse 让这个群体的人们学 R 变得 *更难***。
这里似乎出现了格式问题，这个强调加粗的方式在 Github 的评论里显示没有问题，但在网站的渲染结果上出了问题，请看网站预览效果

<img width="825" alt="截屏2020-10-18 上午11 31 34" src="https://user-images.githubusercontent.com/12031874/96358068-bd315d80-1135-11eb-8cad-a828225de4d6.png">

2020-10-18 03:34 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +## <a name="teachable"> </a> 可教学性
`<a name="teachable"> </a>` 这个应该可以去掉

2020-10-18 03:38 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +如此，教员有太多东西需要解释——包、数据框、**ggplot()**、**aes** 参数、`+` 的作用（在这里并不表示加法）等等——因此教员也许本不该在第一堂课就展示这种用法。
全文的 R 包可以统一加粗表示，比如 **ggplot2**，函数可以带上括号放在代码块引用里 `ggplot()`，函数的参数可以不用加粗，特殊的函数可以不用带上括号，比如文章中出现的加号 `+` 和中括号 `[` 等

2020-10-18 03:41 UTC, XiangyunHuang requested changes
我提了一些格式上的修改建议

2020-10-18 03:47 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +author: "Norm Matloff"
author: 字段里改为

```
作者：Norm Matloff，译者：李嵩，审校：任焱、黄湘云
```

2020-10-18 03:49 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +## 注意：此为简版
这一段可以稍微介绍一下非简版或者提供非简版地址

2020-10-18 03:52 UTC, XiangyunHuang reviewed
还请 @Ryanna-github 多顺一顺语句

2020-10-19 01:54 UTC, boltomli commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +## 注意：此为简版
英文原文全文的链接在后面有提供。

2020-10-19 02:24 UTC, boltomli commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +* RStudio 提倡 Tidyverse 的时候声称它能够使非程序员更容易学习 R。出于上述原因，与之正相反，**我要提出异议：Tidyverse 让这个群体的人们学 R 变得 *更难***。
试了试另一种方法，不行的话我就把这个拿到加粗外面好了。

2020-10-21 10:39 UTC, XiangyunHuang requested changes
@Ryanna-github 你再看下，如果没问题就准备微信端编辑吧

2020-10-21 10:39 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +author: "作者：Norm Matloff，译者：李嵩，审校：任焱、黄湘云"
抱歉我的锅，请再修改一下，添加一行

```
meta_extra: "译者：李嵩；校对：任焱、黄湘云；编辑：任焱"
```

另外，作者字段仅保留原作即可

```
author: "Norm Matloff"
```

2020-10-21 10:45 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +author: "作者：Norm Matloff，译者：李嵩，审校：任焱、黄湘云"
ok，我明天再检查一遍然后编辑~

2020-10-21 14:11 UTC, yihui reviewed
翻译总体来说挺好的。译者和审校辛苦了！Norm 预计这篇文章会收到负面的评价，不过我估计不会太负面。Tidyverse 的宣传攻势对英文社区的影响比较大，而中文用户可能恰好由于语言障碍而获得了自然的免疫，反而会有更客观的评价。我们拭目以待。

2020-10-21 14:11 UTC, yihui commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 概括性不充分。
这三点原因中，我严重怀疑第一点是否能让人看懂，“材料”这样直译可能会让人一头雾水，最好具体一点，比如 Tidyverse 包含的新函数和新概念太多。

第三点的“概括性”一词从何而来呢？原文是 generalizability，应该是某种推广性，具体怎么译，需要结合上下文好好想想，但我没时间帮忙细想。

2020-10-21 14:18 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 概括性不充分。
generalizability 突然想到一个**高级词** 泛化能力 😆

2020-10-21 18:52 UTC, yihui commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 概括性不充分。
这个有点机器学习的意思了，哈哈。

2020-10-22 04:20 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +远不止于此，我对人们如何学习有浓厚的兴趣，从孩童到中年。除了上述课程以外，我还教过移民成年人作为第二语言的英语，他们大多数没有完成高中教育。
```suggestion
除此以外，我从小到大对人们如何学习有浓厚的兴趣。除了上述课程以外，我还给成年移民者教过英语作为第二语言，而他们大多数没有完成高中教育。
```

2020-10-22 04:23 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +来看一下我的在线 R 教程 [**fasteR**](http://github.com/matloff/fasteR)。比如，考虑下面这样无害的一行
```suggestion
来看一下我的在线 R 教程 [**fasteR**](http://github.com/matloff/fasteR)。比如，考虑下面一行
```
这里如果直译从中文看会有一些奇怪，建议直接去掉“无害”这样的词汇，会更加通顺

2020-10-22 04:36 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +`tapply()` 是在 R 语言里最常使用的函数之一。如下所示，不知出于什么原因，Tidy 倡导者不喜欢这个函数，然而这简直是 R 初学者最好用的函数。
```suggestion
`tapply()` 是在 R 语言里最常使用的函数之一。如下所示，可以说它是对 R 初学者来说最好用的函数，但出于某些原因，Tidy 倡导者并不喜欢这个函数。
```

2020-10-22 04:55 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +关于这个话题，一个有趣的讨论见 [Charavarty 和 Keller](https://www-ps.informatik.uni-kiel.de/~mh/reports/fdpe02/papers/paper15.ps.gz)。其实他们支持在 CS 专业的编程绪论课堂中使用 FP，但两位作者的目标和学习 R 的人正好是对立的。作者们列出了三个目标，其中一个是讲授计算机科学理论，一般性的讲授
```suggestion
关于这个话题，一个有趣的讨论见 [Charavarty 和 Keller](https://www-ps.informatik.uni-kiel.de/~mh/reports/fdpe02/papers/paper15.ps.gz)。其实他们支持在 CS 专业的编程绪论课堂中使用 FP，但两位作者的目标和学习 R 的人正好是对立的。作者们列出了三个目标，其中一个是讲授计算机科学理论，对 R 的一般性教学来说，这是不可取的，更不要说教没有编写代码经验的人学习 R 语言。他们承认，即使是对 CS 学生来说，FP 的一个关键概念 *递归* 也是“显著的障碍”。
```

2020-10-22 05:10 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 复杂，需要展现的材料量大。
```suggestion
1. 复杂，Tidyverse 中新函数新概念太多。
```

2020-10-22 05:16 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 概括性不充分。
```suggestion
1. 可拓展性弱。
```
我理解的应该是指想学习 Tidyverse 需要了解各个函数的细节，而难以学少量的几个就可以推广到其他函数和场景。不知道用可拓展性是否合适。求助 @XiangyunHuang “泛化能力差”，“可拓展性弱”，“可推广性弱”哪一个应该更准确？

2020-10-22 05:18 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +但是，Tidyverse 应被视为高级的 R，不是为了初学者，就像大多数复杂的 CRAN 包一样，并且应该作为 *选项* 被呈现，而非 *必须* 的方式。
```suggestion
但是，Tidyverse 应被视为高级的 R，不是面向初学者的入门级别的 R，就像大多数复杂的 CRAN 包一样，Tidyverse 应该作为 *选项* 被呈现，而非 *必须* 的方式。
```

2020-10-22 05:27 UTC, Ryanna-github reviewed
再一次通顺全文语句，但文章末尾的 "Inadequate generalizability" 翻译问题还没有确定。
另外，文章多处格式不一致（不影响阅读），如有的地方 `tapply()` 有的地方是 tapply()，但是英文原版就有这样的问题，故出于尊重原文没有多加修改。

2020-10-22 09:36 UTC, boltomli commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +远不止于此，我对人们如何学习有浓厚的兴趣，从孩童到中年。除了上述课程以外，我还教过移民成年人作为第二语言的英语，他们大多数没有完成高中教育。
这里我比较犹豫，似乎从小到大是修饰学生的。

2020-10-22 13:34 UTC, Ryanna-github commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +远不止于此，我对人们如何学习有浓厚的兴趣，从孩童到中年。除了上述课程以外，我还教过移民成年人作为第二语言的英语，他们大多数没有完成高中教育。
抱歉我之前确实理解有误了，改为“除此以外，我对人们如何学习有浓厚的兴趣，无论他们是孩童还是中年人”是否更合适？

2020-10-22 15:19 UTC, XiangyunHuang approved these changes

2020-10-23 01:44 UTC, XiangyunHuang commented on content/post/2020-10-13-alternative-view-tidyverse-r/index.md
> +1. 概括性不充分。
泛化能力差更准确些

2020-10-27 23:39 UTC, Ryanna-github commented
@boltomli 你好~这篇文章微信端已经编辑完成，劳烦检查，[预览版链接](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA4NF8vL01CY0ZPekZMclhzQ281NW9WTl8yRkJsdzFKOXZmU1dQR1RkVXdTR3pFWDd0dENBaTZHdEdNelhnZGxTRlBUeHVGVzhsMi1Qd0F5MWMyeEloNDdpVmNjdUd1RnRRdXFlUUt2MTFra2pTWVRCeklDUzBXb0hVRGxyQnJ3OG1kZ1Bvd0oxYVhiTUpTajRaNGZoQXdoem5TRmdIQXZMNlBkdlN2UDZnfn4%3D&chksm=3e859bfa09f212ece51df340bed61ad2f4d2108be4fb8452accac8f41f623a5936a916b6ca7c&mpshare=1&scene=1&srcid=1028bfisfHxyEZZrtiXOc1BD&sharer_sharetime=1603841755120&sharer_shareid=754e412dc1add886eee2a727968f84ba#wechat_redirect)

2020-10-28 05:34 UTC, boltomli commented
> @boltomli 你好~这篇文章微信端已经编辑完成，劳烦检查，[预览版链接](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA4NF8vL01CY0ZPekZMclhzQ281NW9WTl8yRkJsdzFKOXZmU1dQR1RkVXdTR3pFWDd0dENBaTZHdEdNelhnZGxTRlBUeHVGVzhsMi1Qd0F5MWMyeEloNDdpVmNjdUd1RnRRdXFlUUt2MTFra2pTWVRCeklDUzBXb0hVRGxyQnJ3OG1kZ1Bvd0oxYVhiTUpTajRaNGZoQXdoem5TRmdIQXZMNlBkdlN2UDZnfn4%3D&chksm=3e859bfa09f212ece51df340bed61ad2f4d2108be4fb8452accac8f41f623a5936a916b6ca7c&mpshare=1&scene=1&srcid=1028bfisfHxyEZZrtiXOc1BD&sharer_sharetime=1603841755120&sharer_shareid=754e412dc1add886eee2a727968f84ba#wechat_redirect)

您好，《Tidy 推广者不希望 R 初学者学习什么》一节中有一个 plot() 和 tapply() 仍为加粗显示，按审稿的建议，以改成代码段为好，请确定。

2020-10-28 06:09 UTC, Ryanna-github commented
@boltomli [已更新](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA4NF92T0s3YzA4eERnYlZ4VU5qNW9WTl8yRkJsdzFKOXZmU1dQR1RkVXdTR3pFWDd0dENBaTZHdEdNelhnZGxTRlBUeHVGVzhsMi1Qd0F5MWMyeEloNDdpVmNjdUd1RnRRdXFlUUt2MTFra2pTWVRCeklDUzBXb0hVRGxyQnJ3OG1kZ1Bvd0oxYVhiTUpTajRaNGZCMVJOdGVKclM1OU81TzJuSlZxQWZBfn4%3D&chksm=3e859bfa09f212ece51df340bed61ad2f4d2108be4fb8452accac8f41f623a5936a916b6ca7c&mpshare=1&scene=1&srcid=1028MVbYLmPOV21BBx7BTvbu&sharer_sharetime=1603865281856&sharer_shareid=754e412dc1add886eee2a727968f84ba#wechat_redirect)

2020-10-29 15:03 UTC, Ryanna-github commented
没有收到其他修改意见，文章预计10月31日（星期六）晚上发出，还劳烦译者 @boltomli 在文章发送后告知原作者~

2020-10-31 23:12 UTC, merged

2020-11-01 02:49 UTC, yihui commented
对应的论坛帖子呢？又忘了按楼顶的检查清单走哦。

2020-11-01 09:41 UTC, XiangyunHuang commented
@Perfectizer 稍后会添加一下帖子和发微博

2020-11-02 02:45 UTC, boltomli commented
> 没有收到其他修改意见，文章预计10月31日（星期六）晚上发出，还劳烦译者 @boltomli 在文章发送后告知原作者~

主站链接已告知作者 <https://github.com/matloff/TidyverseSkeptic/issues/22>