Create dt-pd.rmd
cosname/cosx.org pull request #912
Opened 2020-11-14 03:57 UTC by ShichenXie

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2020-11-14 04:48 UTC, yufree commented
感谢投稿，目前文件名与文件格式有点问题，需要转成`md`文档，否则无法预览，谢谢！

2020-11-14 07:12 UTC, ShichenXie commented
> 感谢投稿，目前文件名与文件格式有点问题，需要转成`md`文档，否则无法预览，谢谢！

因为使用到了分栏（[参见原来的页面](http://shichen.name/post/dt-pd/)），md好像实现不了吧。

2020-11-14 14:12 UTC, yufree commented
可以参考 #858 生成html，主站目前并不支持 rmd 的预览，所以无法确认展示效果。

2020-11-14 15:21 UTC, ShichenXie reviewed
刚才上传了html文件，不知道上传成功了没有

2020-11-15 00:08 UTC, yufree commented
好像并没有，我查了一下似乎你那边的 repo 里没有 html ，是否是还没推送到 GitHub？

2020-11-15 15:37 UTC, yufree commented
目前还是无法生成[预览](https://app.netlify.com/sites/cosx/deploys/5fb0853b98ff030007e0fab5)，看了下应该是投稿文件的文件名问题，能否麻烦修改成 "2020-11-15-dt-vs-pd.html"，这样文件名解析应该就能过了。

2020-11-15 17:30 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.html
> +<link href="{{< relref "post/2019-12-26-dt-pd/index.zh.html" >}}index.zh_files/anchor-sections/anchor-sections.css" rel="stylesheet" />
目前还是无法预览，这里是否需要修改下？`index.zh.html` 这个文件应该是不存在的，对应的 `index.zh_files/anchor-sections/anchor-sections.css` 文件是没有的，包括下一行的js，可否直接删了这两行？

2020-11-16 01:20 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.html
> +<link href="{{< relref "post/2019-12-26-dt-pd/index.zh.html" >}}index.zh_files/anchor-sections/anchor-sections.css" rel="stylesheet" />
已经修改了。对这套系统不是很熟悉，我是直接把自己blogdown生成的文件上传了。

另外cos不也是blogdown生成的么，为啥不支持rmd呢。

2020-11-16 01:28 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.html
> +<link href="{{< relref "post/2019-12-26-dt-pd/index.zh.html" >}}index.zh_files/anchor-sections/anchor-sections.css" rel="stylesheet" />
似乎还没有改，cos主站确实是blogdown生成的，不过blogdown是通过把rmd文档编译成html或md后传给Hugo来实现静态网页展示的，而Hugo本身是不支持rmd文档前端展示的，因此只推送rmd文档Hugo并不会编译。所以投稿可以接受rmd，但必须有对应html或md文档，网站更新在服务器端是不会运行blogdown而仅仅运行Hugo的。

2020-11-16 14:56 UTC, yufree commented
感谢作者修改，目前可以预览了，就是时间有点滞后，审稿会在 rmd 文件上进行，文字如有修改后麻烦作者重新生成下 html。@tcgriffith 有时间看下这篇吗？

2020-11-16 16:00 UTC, ShichenXie commented
那个时间是我最早发在博客上的时间，我更新到11-15日吧

2020-11-16 16:02 UTC, yufree commented
> 那个时间是我最早发在博客上的时间，我更新到11-15日吧

没问题，辛苦了！

2020-11-16 23:27 UTC, tcgriffith commented
> 感谢作者修改，目前可以预览了，就是时间有点滞后，审稿会在 rmd 文件上进行，文字如有修改后麻烦作者重新生成下 html。@tcgriffith 有时间看下这篇吗？

最近没空啊😭

2020-11-17 05:59 UTC, XiangyunHuang commented
辛苦任焱 @Ryanna-github 来审一下

2020-11-22 08:30 UTC, XiangyunHuang commented
@ShichenXie 是否有可能类似 https://github.com/cosname/cosx.org/pull/858 提供一个 Rmd 文件和对应的 HTML 文件，这样方便审稿，目前看到 https://github.com/ShichenXie/cosx.org/tree/patch-2/content/post 上传和  PR 过来的文件是这样的
<img width="1265" alt="截屏2020-11-22 下午4 29 39" src="https://user-images.githubusercontent.com/12031874/99898866-f2eed680-2cdf-11eb-9a83-70fffa6534f9.png">

2020-11-22 09:32 UTC, XiangyunHuang commented
@yihui 我也搞不懂 Rmd 格式怎么投稿的，上次 @fyears 是怎么做到的？

2020-11-22 10:08 UTC, ShichenXie commented
我一直以为一个是rmd，另一个是html文件呢。。。

2020-11-22 16:14 UTC, yufree commented
@XiangyunHuang 我理解生成网站只需要html，但 html 需要 rmd 生成，这样审稿放在 rmd 文档上，完成后作者更新 html 推送就可以了，此时有没有 rmd 源文档应该问题不大。目前主站服务器端没有额外跑 R 脚本，所以直接 rmd 投稿目前应该不行。

2020-11-23 00:21 UTC, XiangyunHuang commented
@yufree  明白，文章没什么要修改的，可以进入编辑，只是最近大家都在忙Ｒ会的事情，抽不出空来，文章可能要晚些时候发出来。

2020-11-23 04:00 UTC, yufree commented
> @yufree 明白，文章没什么要修改的，可以进入编辑，只是最近大家都在忙Ｒ会的事情，抽不出空来，文章可能要晚些时候发出来。

文章是否需要修改需要参考审稿人意见，这篇不是翻译也不是观点，需要走审稿流程，如果任焱没时间，我找其他人来审即可。

2020-11-23 04:17 UTC, XiangyunHuang commented
> > @yufree 明白，文章没什么要修改的，可以进入编辑，只是最近大家都在忙Ｒ会的事情，抽不出空来，文章可能要晚些时候发出来。
> 
> 文章是否需要修改需要参考审稿人意见，这篇不是翻译也不是观点，需要走审稿流程，如果任焱没时间，我找其他人来审即可。

任焱运行了一遍文中的代码，她反馈说没问题，她最近也确实挺忙的，我最近也很忙，没有细看。主编最好再找人来审一下吧

2020-11-23 11:57 UTC, songxxiao commented
@ShichenXie 

文章中Python长表转宽表的部分有误，[`pd.pivot_table`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html)是pandas的数据透视表功能，而非数据重塑。正确的长表转宽表的方法是[`pandas.DataFrame.pivot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html)

所以文中的

```python
# 长表转宽表
df_w = pd.pivot_table(df, index=['Hair','Sex'], columns='Eye', values='Freq', aggfunc = sum).reset_index()
```

应改为：

```python
# 长表转宽表
df_w = df.pivot(index=['Hair','Sex'], columns='Eye', values='Freq').reset_index()
```

2020-11-23 11:59 UTC, songxxiao reviewed
@ShichenXie 

文章中Python长表转宽表的部分有误，[`pd.pivot_table`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html)是pandas的数据透视表功能，而非数据重塑。正确的长表转宽表的方法是[`pandas.DataFrame.pivot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html)

所以文中的

```python
# 长表转宽表
df_w = pd.pivot_table(df, index=['Hair','Sex'], columns='Eye', values='Freq', aggfunc = sum).reset_index()
```

应改为：

```python
# 长表转宽表
df_w = df.pivot(index=['Hair','Sex'], columns='Eye', values='Freq').reset_index()
```

2020-11-23 13:35 UTC, ShichenXie commented
> @ShichenXie
> 
> 文章中Python长表转宽表的部分有误，[`pd.pivot_table`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html)是pandas的数据透视表功能，而非数据重塑。正确的长表转宽表的方法是[`pandas.DataFrame.pivot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html)
> 
> 所以文中的
> 
> ```python
> # 长表转宽表
> df_w = pd.pivot_table(df, index=['Hair','Sex'], columns='Eye', values='Freq', aggfunc = sum).reset_index()
> ```
> 
> 应改为：
> 
> ```python
> # 长表转宽表
> df_w = df.pivot(index=['Hair','Sex'], columns='Eye', values='Freq').reset_index()
> ```

- pivot函数不支持汇总函数，而pivot_table支持与dcast一致；
- pd.pivot_table与pd.melt都可以pd.形式使用，而pivot只能以df.pivot形式

2020-11-23 13:53 UTC, songxxiao commented
@ShichenXie 

感觉传统意义上的数据转换是这种：

```python
>>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
...                            'two'],
...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
...                    'baz': [1, 2, 3, 4, 5, 6],
...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
>>> df
    foo   bar  baz  zoo
0   one   A    1    x
1   one   B    2    y
2   one   C    3    z
3   two   A    4    q
4   two   B    5    w
5   two   C    6    t

>>> df.pivot(index='foo', columns='bar', values='baz')
bar  A   B   C
foo
one  1   2   3
two  4   5   6
```

好像教科书里是把`pivot`和`pd.melt`对应起来的。

2020-11-23 13:59 UTC, ShichenXie commented
@songxxiao 是的，pandas的sheatsheet里面也是将df.pivot和pd.melt对应的，但是与data.table的dcast功能不匹配。

2020-11-23 14:10 UTC, songxxiao commented
@ShichenXie 
嗯嗯，之前没用过`pivot_table`，没想到功能更强大。`dcast`也是个非常强大的函数。文章里或许详细说明一下`df.pivot`和`pivot_table`的异同会更好(尤其是对不熟悉的读者)？

2020-11-23 14:42 UTC, yufree commented
@XiangyunHuang 理解，开放审稿目的是让读者能更好理解内容，扩大受众并保留良性讨论记录，审稿人可以就所有存疑的地方与作者进行讨论，专家视角与读者视角都有助于文章质量提升。而文章下讨论可看作发表后审稿，这样可以最大程度提高文章内容及作者的影响力并保障文章持续更新的动力。

宋骁 @songxxiao 既然来了就来帮忙看下稿子吧。

2020-11-23 14:49 UTC, songxxiao commented
@yufree 
好的！时间不紧的话我通读一遍文章，运行一下代码。

2020-12-20 06:26 UTC, songxxiao approved these changes

2020-12-20 06:45 UTC, songxxiao requested changes

2020-12-20 06:45 UTC, songxxiao commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
似乎应改为
```python
df.groupby('Sex').agg({'Freq':'sum'})\
  .rename(columns={'Freq':'freq_total'})\
  .reset_index()
```

2020-12-20 09:47 UTC, ShichenXie reviewed
嗯嗯，有道理

2021-01-16 04:13 UTC, songxxiao commented
这篇文章我这边运行了所有代码都没问题，请问需要怎么操作？

2021-01-16 14:01 UTC, yufree commented
感谢 @songxxiao 审稿，目前已不需要进一步操作，@ShichenXie 能否修改下最后一个评论，这样我们就直接进入编辑阶段，谢谢！

2021-01-16 14:36 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
> 感谢 @songxxiao 审稿，目前已不需要进一步操作，@ShichenXie 能否修改下最后一个评论，这样我们就直接进入编辑阶段，谢谢！

我记得已经修改了吧

2021-01-16 14:48 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
预览中并未修改，rmd 文档也没有收到更改，能否重新尝试一下？另外文章应有一个分类，可设定为 R 语言。谢谢！

2021-01-16 16:53 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
这次应该更新上了。另外文章分类在哪里修改，不是tags么

2021-01-16 18:14 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
> 这次应该更新上了。另外文章分类在哪里修改，不是tags么

是 yaml 里的 categories，否则会[显示](https://deploy-preview-912--cosx.netlify.app/2020/11/dt-pd/)未分类，另外如果您同意可以在[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml)加入个人信息。

2021-01-16 23:57 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.rmd
> +  reset_index()
都修改好了

2021-01-17 00:31 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.rmd
> +categories: R语言
是我没说清楚，此处应为 `categories:  ['R语言']`，否则 hugo 编译会出[错](https://app.netlify.com/sites/cosx/deploys/60037aa8495dfb000748fccd)而无法生成预览。

2021-01-17 00:44 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.rmd
> +categories: R语言
这回好了

2021-01-17 00:55 UTC, yufree commented
好的，谢谢! @ShichenXie 
请 @XiangyunHuang 安排微信端编辑，@Perfectizer 准备论坛ID，添加审稿人宋骁与对应编辑，这篇下周内发出。

2021-01-17 00:55 UTC, yufree approved these changes

2021-01-17 07:33 UTC, XiangyunHuang commented
@yufree 我让任焱 @Ryanna-github 帮忙编辑一下

2021-01-17 07:36 UTC, Ryanna-github commented
> @yufree 我让任焱 @Ryanna-github 帮忙编辑一下

微信编辑[预览版本](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA5Nl9wb3ROUjBBOTh0Z3BoWmZZUnA1N3pQeFZLa1VZZlFxTm04cWxiSWF1NkE1dFB3UG5qQWFTTkZYdXg1UXcxdU5KNFZ0R1lRZTdLX3BuQk96R1dNWGh6MS11bUEwaUdTZTRPUjQ0YnFIbVRhRXFrYzBPQ3U0ZHo4SmdUem9nTDFSaUFWZTEzeURrakU3Q18zSjREWG5yNGQ1UGVZNU5sTEVBcnczZ2lnfn4%3D&chksm=3e85937d09f21a6bcedb1c9a8cf41a85c0bbec26b9a5cbac28c337ebbefe3cfd2f0230440bb7&mpshare=1&scene=1&srcid=01175aRh6167p8Mt217bOI90&sharer_sharetime=1610868835632&sharer_shareid=754e412dc1add886eee2a727968f84ba&key=&ascene=1&uin=&devicetype=Windows+10+x64&version=63010029&lang=zh_CN&fontgear=2)，md 无法显示分栏效果，故做了一些必要的格式调整

2021-01-17 07:48 UTC, ShichenXie commented
> > @yufree 我让任焱 @Ryanna-github 帮忙编辑一下
> 
> 微信编辑[预览版本](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA5Nl9wb3ROUjBBOTh0Z3BoWmZZUnA1N3pQeFZLa1VZZlFxTm04cWxiSWF1NkE1dFB3UG5qQWFTTkZYdXg1UXcxdU5KNFZ0R1lRZTdLX3BuQk96R1dNWGh6MS11bUEwaUdTZTRPUjQ0YnFIbVRhRXFrYzBPQ3U0ZHo4SmdUem9nTDFSaUFWZTEzeURrakU3Q18zSjREWG5yNGQ1UGVZNU5sTEVBcnczZ2lnfn4%3D&chksm=3e85937d09f21a6bcedb1c9a8cf41a85c0bbec26b9a5cbac28c337ebbefe3cfd2f0230440bb7&mpshare=1&scene=1&srcid=01175aRh6167p8Mt217bOI90&sharer_sharetime=1610868835632&sharer_shareid=754e412dc1add886eee2a727968f84ba&key=&ascene=1&uin=&devicetype=Windows+10+x64&version=63010029&lang=zh_CN&fontgear=2)，md 无法显示分栏效果，故做了一些必要的格式调整

最好可以调整为双栏的。另外reference里面的4和7重复了。

2021-01-17 08:02 UTC, Ryanna-github commented
> > > @yufree 我让任焱 @Ryanna-github 帮忙编辑一下
> > 
> > 
> > 微信编辑[预览版本](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA5Nl9wb3ROUjBBOTh0Z3BoWmZZUnA1N3pQeFZLa1VZZlFxTm04cWxiSWF1NkE1dFB3UG5qQWFTTkZYdXg1UXcxdU5KNFZ0R1lRZTdLX3BuQk96R1dNWGh6MS11bUEwaUdTZTRPUjQ0YnFIbVRhRXFrYzBPQ3U0ZHo4SmdUem9nTDFSaUFWZTEzeURrakU3Q18zSjREWG5yNGQ1UGVZNU5sTEVBcnczZ2lnfn4%3D&chksm=3e85937d09f21a6bcedb1c9a8cf41a85c0bbec26b9a5cbac28c337ebbefe3cfd2f0230440bb7&mpshare=1&scene=1&srcid=01175aRh6167p8Mt217bOI90&sharer_sharetime=1610868835632&sharer_shareid=754e412dc1add886eee2a727968f84ba&key=&ascene=1&uin=&devicetype=Windows+10+x64&version=63010029&lang=zh_CN&fontgear=2)，md 无法显示分栏效果，故做了一些必要的格式调整
> 
> 最好可以调整为双栏的。另外reference里面的4和7重复了。

reference 重复已在原链接中修改，分栏我又尝试了一下，一方面不好实现（尝试在 md 里套 html 渲染但效果很差，完全不是本来想要的分栏），另一方面微信多为手机窄屏阅读而不是网页，可能反而不方便？

2021-01-17 08:07 UTC, ShichenXie commented
> > > > @yufree 我让任焱 @Ryanna-github 帮忙编辑一下
> > > 
> > > 
> > > 微信编辑[预览版本](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTA5Nl9wb3ROUjBBOTh0Z3BoWmZZUnA1N3pQeFZLa1VZZlFxTm04cWxiSWF1NkE1dFB3UG5qQWFTTkZYdXg1UXcxdU5KNFZ0R1lRZTdLX3BuQk96R1dNWGh6MS11bUEwaUdTZTRPUjQ0YnFIbVRhRXFrYzBPQ3U0ZHo4SmdUem9nTDFSaUFWZTEzeURrakU3Q18zSjREWG5yNGQ1UGVZNU5sTEVBcnczZ2lnfn4%3D&chksm=3e85937d09f21a6bcedb1c9a8cf41a85c0bbec26b9a5cbac28c337ebbefe3cfd2f0230440bb7&mpshare=1&scene=1&srcid=01175aRh6167p8Mt217bOI90&sharer_sharetime=1610868835632&sharer_shareid=754e412dc1add886eee2a727968f84ba&key=&ascene=1&uin=&devicetype=Windows+10+x64&version=63010029&lang=zh_CN&fontgear=2)，md 无法显示分栏效果，故做了一些必要的格式调整
> > 
> > 
> > 最好可以调整为双栏的。另外reference里面的4和7重复了。
> 
> reference 重复已在原链接中修改，分栏我又尝试了一下，一方面不好实现（尝试在 md 里套 html 渲染但效果很差，完全不是本来想要的分栏），另一方面微信多为手机窄屏阅读而不是网页，可能反而不方便？

实在不行，那也没办法了

2021-01-18 10:18 UTC, XiangyunHuang commented
@Ryanna-github 发一下微信端最终版吧， @ShichenXie 再确认一下，如果没其他问题的话，我再合并

2021-01-18 10:32 UTC, Ryanna-github commented
> @Ryanna-github 发一下微信端最终版吧， @ShichenXie 再确认一下，如果没其他问题的话，我再合并

[最终版](https://t.1yb.co/fgbv)

2021-01-18 12:04 UTC, ShichenXie commented
> > @Ryanna-github 发一下微信端最终版吧， @ShichenXie 再确认一下，如果没其他问题的话，我再合并
> 
> [最终版](https://t.1yb.co/fgbv)

我这边没问题。

2021-01-18 15:12 UTC, XiangyunHuang commented
> > > @Ryanna-github 发一下微信端最终版吧， @ShichenXie 再确认一下，如果没其他问题的话，我再合并
> > 
> > 
> > [最终版](https://t.1yb.co/fgbv)
> 
> 我这边没问题。

OK，那我们明天晚上 8 点 半发出 @Ryanna-github , 请 @Perfectizer 添加论坛帖子 ID

2021-01-18 15:18 UTC, XiangyunHuang commented
士晨@ShichenXie 方便添加你的个人简介到这里吗？谢大前一个位置😄 https://github.com/cosname/cosx.org/blob/fd13d7e802cd89936bbdc8222b12838a400bb9bc/data/members.yaml#L174

2021-01-18 15:45 UTC, ShichenXie commented
> 士晨@ShichenXie 方便添加你的个人简介到这里吗？谢大前一个位置😄

没注意还有顺序，已经重新更新了

2021-01-19 00:41 UTC, Ryanna-github commented
> > > > @Ryanna-github 发一下微信端最终版吧， @ShichenXie 再确认一下，如果没其他问题的话，我再合并
> > > 
> > > 
> > > [最终版](https://t.1yb.co/fgbv)
> > 
> > 
> > 我这边没问题。
> 
> OK，那我们明天晚上 8 点 半发出 @Ryanna-github , 请 @Perfectizer 添加论坛帖子 ID

好的~

2021-01-19 15:09 UTC, XiangyunHuang commented
> > 士晨@ShichenXie 方便添加你的个人简介到这里吗？谢大前一个位置😄
> 
> 没注意还有顺序，已经重新更新了

士晨，我是指把个人简介添加到[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml)，格式样式仿照下方

<img width="1208" alt="截屏2021-01-19 下午11 06 43" src="https://user-images.githubusercontent.com/12031874/105052608-0aadc580-5aab-11eb-8f41-ee6faff7532d.png">

另外，我去微信上 AT 一下林枫 @Perfectizer 让他加一下论坛 ID

2021-01-19 15:44 UTC, ShichenXie commented
> > > 士晨@ShichenXie 方便添加你的个人简介到这里吗？谢大前一个位置😄
> > 
> > 
> > 没注意还有顺序，已经重新更新了
> 
> 士晨，我是指把个人简介添加到[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml)，格式样式仿照下方
> 
> <img alt="截屏2021-01-19 下午11 06 43" width="1208" src="https://user-images.githubusercontent.com/12031874/105052608-0aadc580-5aab-11eb-8f41-ee6faff7532d.png">
> 
> 另外，我去微信上 AT 一下林枫 @Perfectizer 让他加一下论坛 ID

这次应该可以了吧 。。。

2021-01-19 17:13 UTC, Perfectizer commented
@ShichenXie 似乎还没看到更新个人简介。
地址在这里：https://github.com/cosname/cosx.org/blob/master/data/members.yaml
另外，论坛id已添加。

2021-01-19 23:07 UTC, ShichenXie commented
> @ShichenXie 似乎还没看到更新个人简介。
> 地址在这里：https://github.com/cosname/cosx.org/blob/master/data/members.yaml
> 另外，论坛id已添加。

这个怎么更新，不是直接在文件上编辑么？实在不行就算了吧。

2021-01-19 23:47 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.html
> +  -R语言
此处应有空格

2021-01-19 23:48 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.html
> +  -python
此处应有空格

2021-01-20 01:00 UTC, ShichenXie commented on content/post/2020-11-15-dt-vs-pd.html
> +  -python
已经修改了，再试试看

2021-01-20 01:22 UTC, yufree commented on content/post/2020-11-15-dt-vs-pd.html
>  date: '2021-1-19'
我大意了，这里还有个格式问题，应该改为 ‘2021-01-19’
> ERROR 2021/01/20 00:58:26 Failed to parse date '2021-1-19' in page post/2020-11-15-dt-vs-pd.html

2021-01-20 03:37 UTC, merged