投稿: 用“专业”的方式创建和开发你的 R 包 苏玮
cosname/cosx.org pull request #928
Opened 2021-02-15 15:11 UTC by swsoyee

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2021-02-15 15:31 UTC, yufree commented
感谢投稿！确实R包开发这边需要更新新文章了，特别是 `usethis` 这个包极大程度降低了开发门槛，不知道肖版有兴趣看一下吗？@nanxstats

2021-02-16 01:55 UTC, nanxstats requested changes
@yufree 已阅

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +title: 用“专业”的方式创建和开发你的 R 包
建议选用一个更为准确的标题，毕竟没有使用这些工具构建的 package 也不存在不 “专业” 的问题。

例如，强调 usethis, testthat, styler, pkgdown 等工具自动化带来的流程上的便利: Writing R Packages: A Modern Workflow for Beginners

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +slug: create-r-package-in-a-professional-way
same issue

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +4. [如何快速写一个R包](https://www.bioinfo-scrounger.com/archives/546/)
考虑互联网上一般链接的生存时间，建议列举链接前两三个经典的 reference 即可。

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +动机其实也很简单，可能也是由于自己阅读或者搜索深度不够，目前还没有发现一篇说到如何用“专业”的方式来创建 R 包的教程。
「专业」

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +usethis::create_package(path = "../rPackageTutorial")
使用相对路径很好，但在当前目录向上跳一级 `../` 的用法让我感到略为费解

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +![3.2.1. 使用 GitHub Desktop 添加本地项目。](https://s3.ax1x.com/2021/02/15/y6D7PP.png)
所有图片建议遵循惯例使用 GitHub 作为图床

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +### 3.3 用 `{renv}` 进行依赖（加载包）的版本控制
这里存在一个问题：renv 起到了重现 R package dependency version 的作用，但是 DESCRIPTION 文件里并没有相应体现，这样在 development 和 deployment 两个 lifecycle 有所脱节。

2021-02-16 01:55 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +# 如果没有依赖到别的具有不同版权的包的话，一般无脑 MIT 即可
建议对 license 的选择给出建议，「一般无脑 MIT 即可」似有不妥。

2021-02-16 14:38 UTC, yufree commented
辛苦肖版了 @nanxstats ，请作者 @swsoyee 进行回复或修改，谢谢！

2021-02-16 14:40 UTC, swsoyee commented
@nanxstats @yufree 谢谢二位！这个稍微需要一些时间来进行全文调整，修改完毕后会重新更改为 Ready for review🙏

2021-02-16 14:49 UTC, swsoyee commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +动机其实也很简单，可能也是由于自己阅读或者搜索深度不够，目前还没有发现一篇说到如何用“专业”的方式来创建 R 包的教程。
这个个人觉得应该是使用国标好一点，毕竟统计之都的读者是以简体中文用户为主要读者。
[中华人民共和国非强制性国家标准：先用双引号“ ”，内部如需再引用，再用单引号‘’，若再需引用，使用双引号“ ”，以此类推。直排仍保持双引号在外，改用﹃ ﹄和﹁ ﹂。](https://zh.wikipedia.org/wiki/%E5%BC%95%E5%8F%B7#%E5%BD%A2%E7%8B%80)

或者重新调整这一段的遣词造句。这个我再思考一下。

2021-02-16 14:56 UTC, swsoyee commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +usethis::create_package(path = "../rPackageTutorial")
这里出于我本人的一个不太成熟的考虑才使用来向上一级的相对路径。

1. 绝对路径的话涉及系统方面的说明，比较繁琐，不想在本篇里说太多这方面的事情。
2. 因为没有使用 RStudio 图形界面的创建包的流程，向上一级涉及一个常用的情况：很多用户其实在敲打第一条命令（`install.packages("usethis")`）时已经打开了 RStudio（新建了一个 Project 并且设置成了当前工作路径），跳上一级就是为了和第一条命令的工作路径保持新 Package 和现有 Project 保持平行。

虽然不知道我这种想法合不合适，希望肖版能够赐教。

2021-02-16 16:05 UTC, swsoyee commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +### 3.3 用 `{renv}` 进行依赖（加载包）的版本控制
使用了 renv 的项目在打开的时候会自动检查是否安装了相同版本的 renv，如果没有则会自动从 CRAN 上下载相应的包：
```r
# Bootstrapping renv 0.12.5 --------------------------------------------------
* Downloading renv 0.12.5 from CRAN ... OK
* Installing renv 0.12.5 ... Done!
* Successfully installed and loaded renv 0.12.5.
* Project '~/Desktop/rPackageTutorial' loaded. [renv 0.12.5]
* The project library is out of sync with the lockfile.
* Use `renv::restore()` to install packages recorded in the lockfile.
```
这种情况下似乎就不一定需要把 renv 放到 DESCRIPTION 里的 Suggests 中了（或许是 deployment 阶段需要？）。因为我开发 R 包经验很浅，不知道我的理解是否正确，如果方便的话请肖版赐教 🙏

2021-02-16 17:27 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +动机其实也很简单，可能也是由于自己阅读或者搜索深度不够，目前还没有发现一篇说到如何用“专业”的方式来创建 R 包的教程。
啊，标点没啥问题，只是标注下“专业”需要同上进行修改。

因为下文反复提到这个概念，就没有一一标注了。这里我就标个下同吧。

2021-02-16 17:47 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +usethis::create_package(path = "../rPackageTutorial")
嗯，有些道理。RStudio 的默认 context 是没有打开 project，working directory 是 `~/`，所以我觉得我们在这里也不需要假设有 context，直接 `usethis::create_package(path = "rPackageTutorial")` 较好，最多提一句会在当前工作目录下创建就可以了。

2021-02-16 17:54 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +### 3.3 用 `{renv}` 进行依赖（加载包）的版本控制
嗯，说个个人观点哈，其实原因很简单，renv 更适合用于非 R package 的项目中。

R package 相对比较特殊。假设我们最后要提交到 CRAN，一般的目标应该是对依赖向前兼容。对应的解决方案是在 DESCRIPTION 中声明不带版本或 `>=` 的依赖，然后利用 CI/CD pipeline 去检查集成情况。

2021-02-17 14:09 UTC, swsoyee commented
@nanxstats 已做出调整，请肖版再次过目😃

2021-02-18 17:23 UTC, nanxstats reviewed
修改后的版本解决了我之前提的问题，整体上感觉不错，推荐发表。

2021-02-18 17:23 UTC, nanxstats commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +![3.5.1 在 `R` 文件夹h中创建 `add.R` 文件用于保存函数，点击 `Insert Roxygen Skeleton` 快速生成。](https://raw.githubusercontent.com/swsoyee/rPackageTutorial/main/man/figures/3.5.1.png)
`文件夹h`?

2021-02-19 01:05 UTC, swsoyee commented on content/post/2021-02-16-create-r-package-in-a-professional-way.md
> +![3.5.1 在 `R` 文件夹h中创建 `add.R` 文件用于保存函数，点击 `Insert Roxygen Skeleton` 快速生成。](https://raw.githubusercontent.com/swsoyee/rPackageTutorial/main/man/figures/3.5.1.png)
不好意思，错字已修复

2021-02-19 01:58 UTC, yufree commented
感谢肖版的审稿与作者的修改，审稿阶段结束，下面转到编辑阶段，预计正月十五左右发出。@Perfectizer @XiangyunHuang

2021-02-23 13:01 UTC, Li705772676 commented
您好，这是编辑好的推送链接。您看有什么地方需要修改吗，预计明天或后天发出。
https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTEwMV9aaWJnNldXOGNrTm53K2lucjdyNlFQWklJbzJzMVYyanVTR0Y5VjhCZ3Z5UWszd3R5NEpIR3NpRUZqVjQyRExVMGloNFNTYmRhblRVSHZBakUycnFRMDFXeXlaUjRRSndBcE54YUwyeXRweTdfQUNOUWRQQXBzX1EyTG1mQUVSd2ZUTGswNG5HTjdON3BkcG8tSjJFbnIxN0JxN3BvX3lMY0ZSRWFRfn4%3D&chksm=3e8593c609f21ad0aa20c2f300d30113afdebf4fc689094f17aa1a70952d89d3733c31312a96#rd

2021-02-23 13:47 UTC, swsoyee commented
> 您好，这是编辑好的推送链接。您看有什么地方需要修改吗，预计明天或后天发出。
> https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTEwMV9aaWJnNldXOGNrTm53K2lucjdyNlFQWklJbzJzMVYyanVTR0Y5VjhCZ3Z5UWszd3R5NEpIR3NpRUZqVjQyRExVMGloNFNTYmRhblRVSHZBakUycnFRMDFXeXlaUjRRSndBcE54YUwyeXRweTdfQUNOUWRQQXBzX1EyTG1mQUVSd2ZUTGswNG5HTjdON3BkcG8tSjJFbnIxN0JxN3BvX3lMY0ZSRWFRfn4%3D&chksm=3e8593c609f21ad0aa20c2f300d30113afdebf4fc689094f17aa1a70952d89d3733c31312a96#rd

谢谢，在最后的底部作者信息处我更新了一下添加了我个人博客的链接 b5b5b1c ，如果可以的话能否添加上去呢？

2021-02-23 13:50 UTC, Li705772676 commented
> > 您好，这是编辑好的推送链接。您看有什么地方需要修改吗，预计明天或后天发出。
> > https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTEwMV9aaWJnNldXOGNrTm53K2lucjdyNlFQWklJbzJzMVYyanVTR0Y5VjhCZ3Z5UWszd3R5NEpIR3NpRUZqVjQyRExVMGloNFNTYmRhblRVSHZBakUycnFRMDFXeXlaUjRRSndBcE54YUwyeXRweTdfQUNOUWRQQXBzX1EyTG1mQUVSd2ZUTGswNG5HTjdON3BkcG8tSjJFbnIxN0JxN3BvX3lMY0ZSRWFRfn4%3D&chksm=3e8593c609f21ad0aa20c2f300d30113afdebf4fc689094f17aa1a70952d89d3733c31312a96#rd
> 
> 谢谢，在最后的底部作者信息处我更新了一下添加了我个人博客的链接 [b5b5b1c](https://github.com/cosname/cosx.org/commit/b5b5b1c9dd086cca9c573e62ff85fcae1d7e5b4d) ，如果可以的话能否添加上去呢？
>
> 好的，收到~

2021-02-23 13:54 UTC, XiangyunHuang commented on content/post/writing-r-packages-a-modern-workflow-for-beginners.md
> +meta_extra: ""
麻烦 @swsoyee 添加一下 `meta_extra: "审稿：肖楠；编辑：李旋"`

2021-02-23 13:55 UTC, XiangyunHuang approved these changes

2021-02-24 12:49 UTC, merged