投稿: "用 R 包 gm 创作音乐" flujoo
cosname/cosx.org pull request #937
Opened 2021-04-09 20:04 UTC by flujoo

I have to include audio files with HTML

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2021-04-10 23:48 UTC, yufree commented
感谢投稿，请任焱师妹审稿 @Ryanna-github

2021-04-10 23:53 UTC, yufree commented
感谢投稿！印象中大鹏老师 @pzhaonet 做过乐谱相关的包，有时间看下这篇文章吗？或者推荐下懂音乐的审稿人？谢谢！

2021-04-11 05:28 UTC, flujoo commented
谢谢! 这里是该包的完整文档 <https://flujoo.github.io/gm/articles/gm.html> 也许对审稿有帮助.

2021-04-12 02:18 UTC, pzhaonet commented
@yufree 遵旨。

2021-04-12 03:22 UTC, pzhaonet requested changes
这个包非常有趣，介绍文字也很友好。建议做适当修改。

2021-04-12 03:22 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +
这里以及下文最好每步都展示一下运行 `show(m)`的结果，能直观看到每步的意义。

2021-04-12 03:22 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +加上旋律线：
似乎应为“增加谱表”。“旋律线”一词或许另有所指。下同。

2021-04-12 03:22 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +4. ......
第 4 条可以删掉。

2021-04-12 03:22 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +- gm 的语言更简单直观，结合上面这点，gm 更适合音乐编程。
此处对比的话，可以考虑用表格的形式，如：

功能 | tabr | gm
--- | --- | ---
生成音乐 | √ | √
分析音乐 | √ | ×

或者用原文的列表，但每条务必两个包都要提及，并且先后顺序保持一致，例如第 1 条可改为：

> gm 仅能生成音乐，而 tabr 除了生成音乐，还可以分析音乐；

2021-04-12 03:22 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +从这个例子你也可以感受到，gm 利用 R 的基本数据结构来表征音高和时值，语法简单，非常适合用编程的方式产生音乐。
文末戛然而止，似乎没写完。建议加上一段结语。或者将“与其它包的比较”一节移至文末，例如：

> 综合来说，虽然 gm 目前还不足以作为专业级别的记谱软件使用，然而它具备了语言高阶简单的优点，并且适用于常见的 R 工作环境，希望你会喜欢。

或者稍微展望一下：

> 综合来说，gm 的优点是，语言高阶简单，并且适用于常见的 R 工作环境。而如果你想要专业级别的记谱软件，gm 目前还不够，希望在未来能够不断完善。

2021-04-12 04:47 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +title: "用 R 包 gm 创作音乐"
大鹏老师, 你好, 谢谢你的修改意见! 很多意见也适用于我在其它场合的文档. 下面只对我觉得有待讨论的地方回复.

关于包的功能, 我坚持是 "创作音乐", 或者抽象模糊一点, "写音乐". 或至少是 "生成音乐". 原因:

1. 总体来说, 虽然这个包不直接提供算法作曲的工具, 但它提供了一套高阶地表达音乐的语言, 这背后的目的是为了让表达音乐更方便, 而不是让表达乐谱更方便. 虽然生成的结果往往以乐谱呈现, 那这也仅仅是因为乐谱是非常通用的表征音乐的方式, 我完全可以转化成 piano roll 的形式. 但核心依然是对音乐的高阶表达.
2. 如果要定位成 "制作乐谱", 这个包会欠缺很多乐谱制作技术上的功能, 这些功能哪怕在以后的迭代中, 我也不会考虑.
3. "记录音乐" 又容易联想到 recording.
4. 可以类比一下 ggplot2. "作图", "画图", 那么对应过来最类似的应该是 "写音乐".

2021-04-12 04:51 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +
这里有个技术问题, m 如果没有拍号和声部在其中, 是没法 show 的. 但我也许可以 print, 以达到你说的目的.

2021-04-12 04:56 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +加上旋律线：
这里我坚持是 "旋律线/声部 (musical line)".

1. 旋律线或声部是对音乐结构的描述, 而谱表则是对乐谱的描述. 严格来说, 音频这种表征中就不存在谱表这种东西.
2. 在 gm 中, 声部最后可以在谱中变成 part, staff, voice 三种状态, 所以哪怕是从乐谱角度考虑, 也不能用 "谱表".
3. musical line 是通用的术语, 更一般性.

更多技术细节可见完整文档中的 [Multiple Line Objects](https://flujoo.github.io/gm/articles/gm.html#multiple-line-objects-1)

2021-04-12 05:36 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +- gm 的语言更简单直观，结合上面这点，gm 更适合音乐编程。
表格这个建议我又想了一下，可能有点不适合。一个是我并没有深入对比两个包所有特点，而表格会给人一种“盖棺定论”的误导。二是列出来的几点用你提供的格式来制作表格会套入不进去，比如两个包的表征音乐的方式。所以我建议还是用 list 的形式来笼统地比较可能更好。

2021-04-12 05:58 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +title: "用 R 包 gm 创作音乐"
谢谢答复！“写音乐”很有道理，就是感觉一般不这么搭配，可能会引起费解。我觉得“记录音乐”是比较确切的。如果担心跟“录音”混淆，不知说“制作音乐”怎么样？好比“作图”、“画图”也可以说是“制作图表”。

2021-04-12 06:06 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +title: "用 R 包 gm 创作音乐"
制作音乐会让人想到 [music production](https://www.coursera.org/specializations/music-production), 会联想到 Logic Pro 那样的音乐制作的程序。

英文我是用 create，generate，其实理解起来还好，翻译过来可能总差点味道。但我还是建议采用笼统、日常而非精确的翻译。目前来看，可能“生成”更好。一个是不管是乐谱还是音频都是“生成”出来的，而非制作或录音出来的，也不是直接描述乐谱本身打谱出来。二是它没有“创作”那层算法的意味。

2021-04-12 06:08 UTC, pzhaonet commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +MuseScore 有[默认的安装路径](https://musescore.org/en/handbook/3/revert-factory-settings)，如果你下载到其它路径，请在 .Renviron 文件中设置：
"，如果你下载到其它路径"改为“。如果安装到了其它路径”

2021-04-12 06:09 UTC, flujoo commented on content/post/2021-04-09-create-music-with-r-package-gm.md
> +MuseScore 有[默认的安装路径](https://musescore.org/en/handbook/3/revert-factory-settings)，如果你下载到其它路径，请在 .Renviron 文件中设置：
抱歉，我漏看了。

2021-04-12 06:11 UTC, pzhaonet commented
我没有意见了。愉快地玩这个包去了。

2021-04-12 06:16 UTC, flujoo commented
@pzhaonet 谢谢大鹏老师！

2021-04-12 15:19 UTC, yufree commented
感谢大鹏老师 @pzhaonet 的审稿与作者 @flujoo 的修改！作者可在[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml) 提供个人信息，然后我们就转入编辑阶段了。

2021-04-12 16:26 UTC, flujoo commented
@yufree 已修改，感谢

2021-04-14 13:26 UTC, yufree commented
额，其实自我介绍可以放在同一次PR中，且建议实名。请 @XiangyunHuang 安排微信编辑，@Perfectizer 准备主站推送。

2021-04-15 01:28 UTC, XiangyunHuang commented
> 额，其实自我介绍可以放在同一次PR中，且建议实名。请 @XiangyunHuang 安排微信编辑，@Perfectizer 准备主站推送。

收到

2021-04-18 05:47 UTC, YueeXiang commented
这是微信端的[预览链接](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTEwOV9QSUxlOUppcUwwZE1XYkVoUUJSa3RBcW9JZVY5MUFyN0NfWVlXLWxDLXh3MXNBS3dzUG05bHREbGE2cF9SRFBPNENHaWVJVnN0QTR3SVhibldhVHVjWGhiMUhyR2ZCa3laVGw5bURBcnVCZlZVTi1wdWRlbXB1d1pwN0g2RkVBX0F2ejV0Sy0wNGFiM05WU3BnbkZEZE9rOW9RaE1qLXFoalpQRUFBfn4%3D&chksm=3e85906509f21973fc590f919dd65e54234f8ef7fbe54b41acef20b5aac90a0885c96caf1c80&mpshare=1&scene=1&srcid=0418ooGTJ3aiTFsjUMWXPIgx&sharer_sharetime=1618723750318&sharer_shareid=a8d6784ce5af159b4e2a98ca7d7947ae#wechat_redirect)，请大家检查~

2021-04-18 15:24 UTC, flujoo commented
@YueeXiang 多谢! 有两个音频没有显示

2021-04-19 12:12 UTC, YueeXiang commented
@flujoo 抱歉之前编辑的时候疏忽把音频给漏了，现在加上啦！[新的链接](https://mp.weixin.qq.com/s?__biz=MjM5NDQ3NTkwMA==&tempkey=MTEwOV9CUS83OW9PTXd6MmY4R3JMUUJSa3RBcW9JZVY5MUFyN0NfWVlXLWxDLXh3MXNBS3dzUG05bHREbGE2cF9SRFBPNENHaWVJVnN0QTR3SVhibldhVHVjWGhiMUhyR2ZCa3laVGw5bURBcnVCZlZVTi1wdWRlbXB1d1pwN0dCNVRINWhZYUJoNW9VdGJKQWhnZEJ5S3ZzdnFwc3ZVSElpMGRwZ0FGT2tBfn4%3D&chksm=3e85906509f21973fc590f919dd65e54234f8ef7fbe54b41acef20b5aac90a0885c96caf1c80&mpshare=1&scene=1&srcid=0419tRZYJXjtXqcItUXEjrPK&sharer_sharetime=1618834195487&sharer_shareid=a8d6784ce5af159b4e2a98ca7d7947ae#wechat_redirect)
如果没有别的问题的话，生成主站链接之后就可以发布了~

2021-04-19 12:20 UTC, XiangyunHuang approved these changes

2021-04-19 12:21 UTC, XiangyunHuang commented
@Perfectizer 抽空开帖子吧

2021-04-19 12:21 UTC, merged

2021-04-19 23:59 UTC, pzhaonet commented
> 感谢大鹏老师 @pzhaonet 的审稿与作者 @flujoo 的修改！作者可在[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml) 提供个人信息，然后我们就转入编辑阶段了。

 members 需要资格认证吗？可不可以把我加进去？

2021-04-20 00:05 UTC, yufree commented
> > 感谢大鹏老师 @pzhaonet 的审稿与作者 @flujoo 的修改！作者可在[这里](https://github.com/cosname/cosx.org/blob/master/data/members.yaml) 提供个人信息，然后我们就转入编辑阶段了。
> 
> members 需要资格认证吗？可不可以把我加进去？

当然没问题，大鹏老师直接PR到这个[文件](https://github.com/cosname/cosx.org/blob/master/data/members.yaml)就可以了，或者把个人信息发到编辑部[邮箱](mailto:editor@cosx.org) ，我们来加。

2021-04-20 15:10 UTC, pzhaonet commented
@yufree 已 PR。多谢啦！