投稿：因果推断——现代统计的思想飞跃 丁鹏
cosname/cosx.org pull request #951
Opened 2021-07-02 06:54 UTC by StevenBoys

非常感谢您的PR, 如果您是在为主站投稿, 请将PR的标题改为"投稿:标题+作者的形式",如:
"投稿: 数据通灵术 杜亚磊"
并保留下面的内容.

- 投稿者请注意
  - [ ] 主编审核确认接收
  - [ ] 主编安排审稿人
  - [ ] 审稿、修改

> 至此，投稿部分的工作结束

- 编辑部分工作
  - [ ] 文字编辑做校对工作。需校对文章分类，目前的文章分类包括：**COS访谈，R会议，R语言，推荐文章，新闻动态，机器学习，统计之都，统计图形，统计应用，统计模型，统计计算，统计软件，职业事业**。不得擅自增加分类。
  - [ ] 微信编辑、发布，阅读原文附主站链接，文末附作者介绍
  - [ ] 论坛帖子负责人发帖，粘贴链接，提供 `forum_id` 加入文章
  - [ ] 合并 PR，发布文章

[投稿指南在这里](https://cosx.org/contribute/)，有任何问题，可以直接在PR留言，其他问题请联系: editor@cos.name。

2021-07-02 07:18 UTC, StevenBoys commented
![aristotle](https://user-images.githubusercontent.com/26518047/124236009-95273600-dadb-11eb-912c-fbddee157fcf.jpeg)

2021-07-02 07:20 UTC, StevenBoys commented
![hume](https://user-images.githubusercontent.com/26518047/124236302-e6372a00-dadb-11eb-8e8e-8eda29346d1c.jpg)

2021-07-02 07:21 UTC, StevenBoys commented
![neyman](https://user-images.githubusercontent.com/26518047/124236518-20083080-dadc-11eb-8d21-ac4204e5511f.png)

2021-07-02 07:24 UTC, StevenBoys commented
<img width="824" alt="rubin" src="https://user-images.githubusercontent.com/26518047/124236742-62ca0880-dadc-11eb-8707-2662081022e2.png">

2021-07-02 07:25 UTC, StevenBoys commented
![fisher](https://user-images.githubusercontent.com/26518047/124237095-c94f2680-dadc-11eb-9c85-cb6c86ddc376.jpg)

2021-07-02 07:29 UTC, StevenBoys commented
[dag2.pdf](https://github.com/cosname/cosx.org/files/6752845/dag2.pdf)

2021-07-02 07:31 UTC, StevenBoys commented
![PearlBook](https://user-images.githubusercontent.com/26518047/124237653-5f834c80-dadd-11eb-830f-0b2b81231467.jpeg)

2021-07-02 07:32 UTC, StevenBoys commented
![quyuan](https://user-images.githubusercontent.com/26518047/124237858-9ce7da00-dadd-11eb-81d4-d72107f4e532.jpeg)

2021-07-02 07:34 UTC, StevenBoys commented
![geng](https://user-images.githubusercontent.com/26518047/124238197-e46e6600-dadd-11eb-8efa-ed714eefb8e2.jpeg)

2021-07-02 07:36 UTC, StevenBoys commented
![surrogate](https://user-images.githubusercontent.com/26518047/124238322-0e278d00-dade-11eb-9c3f-ad3cd12e19ed.png)

2021-07-02 18:46 UTC, yufree requested changes
主要是图片标题显示、引用上标与公式目前显示有问题，请仔细核查

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>转载自《数学文化》2021/第12卷第2期
“转载自《数学文化》2021/第12卷第2期” 这个按出版社要求放到引言前面

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +长期以来，人们一方面好奇地追问原因和结果的关系，一方面又苦于这些概念的模糊性。于是，这些话题在很长一段时间都仅仅局限在哲学和文学的范围内。精确地描述因果关系，尤其是用数学的语言来描述因果关系，则是非常近代的事情了。这一项思想飞跃，得益于现代统计学的发展。统计学家称之为“因果推断”（causal inference）。虽然因果推断在现代统计学的萌芽阶段就已经产生，但是它的发展并非一帆风顺：它长期被
这里上标用html吧，用公式环境感觉有点怪，例如 ` <sup>1</sup>`，或者用markdown的footnote应该也可以，例如`因果推断^[1]`。

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +大部分西方哲学家都认为因果关系是一条本质的、似乎毋庸置疑的定律。但是，苏格兰哲学家大卫• 休谟（David Hume, 1711-1776）曾经抛出了一条惊人的论点。简言之，他认为人类仅仅凭经验，只能认识事物之间恒定的前后相继关系（constant conjunction），并不能认识任何因果关系。很多哲学家都努力回应休谟的质疑，因为若是承认休谟是对的，那么知识何以成为可能？若人类的知识仅仅是经
上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>亚里士多德《 物理学》的一个英译本。这本书的 Book II 3 的开篇写道：“Knowledge is the object of our inquiry, and men do not think they know a thing till they have grasped the 'why' of it (which is to grasp its primary cause)”，翻
图片标题用斜体吧，引用环境没有显示 `*亚里士多德《 物理学》的一个英译本。这本书的 Book II 3 的开篇写道：“Knowledge is the object of our inquiry, and men do not think they know a thing till they have grasped the 'why' of it (which is to grasp its primary cause)”，翻译成中文就是，我们探索的目标是知识，只有掌握了“为什么”，才算真正理解一个事物，即，掌握该事物的根本原因。*`

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +人们常常问关于原因和结果的问题。比如，某人死于肺癌，是不是因为他常常吸烟导致的？比如，我感冒症状减轻了，是不是因为服用了维生素C片导致的？比如，大学教育是否能够提高收入水平？类似的问题，充满了我们的日常生活。
维生素C前后有空格

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +但是，这些看似直接了当的问题，却不容易回答。比如，有人吸烟，却没有得肺癌；有人不吸烟，却得了肺癌。比如，我可能仅仅喝白开水，感冒也会自己消失。比如，有人没有上大学，却做生意发了大财。当然，有点概率论常识的人很容易意识到，这些事件都带有随机性。从经验中，我们可能观察到吸烟的人更可能得肺癌；服用维生素C 的人，平均来说，自我感觉感冒恢复得更快；上过大学的人平均收入更高。但是，这些统计上的“相关关系”
维生素C前后有空格

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>休谟的名著《人性论》对哲学史产生了深远的影响，他指出了归纳推理的缺陷，认为我们对因果关系的信念仅仅来自于习惯（habit）和传统（custom）。
图片标题*斜体*

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>年轻时的内曼。内曼是加州大学伯克利分校统计系的创始人（照片由该系提供）。
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +以农业实验为例，考虑 n 块田作为实验的对象，实验者想检测两种肥料对于产量的影响。用i 表示第 i 块田，$Y_i (1)$ 和 $Y_i (0)$ 表示如果用肥料 1 和肥料 0 分别对应的第 i 块田的产量，那么 $\tau_i = Y_i (1) − Y_i (0)$ 就是肥料 1 相对于肥料 0 对第 i 块田产量的因果作用。实验者随机地分配肥料1 或者肥料 0 到第 i 块田，所以最终
公式环境前后用撇号来显示公式，例如 \`$\tau_i = Y_i (1) − Y_i (0)$\`

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +这个τ 通常被称为平均因果作用（average causal effect）。这可能是因果作用最简单的定义了。到此为止，内曼引入了一些数学记号来定义“因果作用”。也许读者会觉得这平平无奇，无非就是 $Y_i (1)$ 和 $Y_i (0)$ 。但是，这些记号将开启一扇窗，迎接新思想的曙光。
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +潜在结果 $Y_i (1)$ 和 $Y_i (0)$ ，以及平均因果作用 $\tau$，在某种意义上，都是假想的数字。仅有这些定义，还不能说明这个模型的现实意义。问题的关键是：我们能否根据观测到的数据推断 $\tau$ ？内曼给出了肯定的回答。在随机化实验下，第 i 块田接受肥料 1 或者肥料 0是完全随机的。用 $Z_i$ = 1 表示第 i 块田接受肥料 1，用 $Z_i$ = 0 表示第
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +这个恒等式似乎显而易见：从数学上讲，它无非说明，当 $Z_i = 1$ 时，$Y_i = Y_i (1)$；当 $Z_i = 0$ 时，$Y_i = Y_i (0)$。 但是，我在和朱迪亚.珀尔（Judea Pearl）交流时，他认为这是因果推断最重要的恒等式，因为它联系了左边我们能够观测到的结果和右边的潜在结果。
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +最终能够被观测的数据是$\{(Z_i, Y_i) : i = 1, \cdots , n\}$。一个显而易见的估计量是
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +它是接受肥料 1 和肥料 0 下，平均结果的差值。内曼证明了 $\hat{\tau}$ 是平均因果作用 $\tau$ 的无偏估计（即 $\hat{\tau}$ 的期望是 $\tau$ ），计算了这个估计量的方差，讨论了如何估计这个方差，还提出了一个基于 $\hat{\tau}$ 的中心极限定理的置信区间（即这个区间以指定的概率盖住真值 $\tau$ ）。最后一步的中心极限定理在内曼的原文仅仅是一
公式环境，脚注

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +内曼生前对自己在统计假设检验方面的奠基性工作颇为自豪，认为那是统计学中“哥白尼式的革命”$（Copernican Revolution）^5$。他并未预料他在因果推断的奠基性工作，也将产生深远的影响。这个影响则是由唐纳德• 鲁宾（Donald Rubin）开启的。
唐纳德•鲁宾 去掉空格，脚注上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +虽然潜在结果模型成功地数学化了随机化实验中的因果推断，但是它长期并未用于观察性研究——内曼本人是持怀疑态度的，因为缺乏随机化，观察性研究有太多复杂性，比如抽烟的人和不抽烟的人，可能就是两群完全不同的人，不具有可比性。虽然他从未尝试用他的潜在结果模型分析观察性数据，但是他间接地启发了一些更加有冒险精神的学者。其中一人就是鲁$宾^6$。
脚注上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>鲁宾教授正在作报告（截屏自https://www.youtube.com/watch?v=N4tQC3elGK4）
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +鲁宾认为，观察性研究也对应着一个假想的随机化实验，因此内曼的潜在结果模型可以用来定义一般的因果作用。这里我们考虑一般的问题，不再局限于农田、肥料和产量。用 i 表示个体i，它的观测结果 $Y_i$ 有两个潜在结果 $Y_i (1)$ 和 $Y_i (0)$，分别对应两个处理水平，一般来说 1 被称为“处理”（treatment），而 0 被称为“对照”（control）。每个个体 i 有一个二值
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
这个公式有问题吧？

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +为了简单起见，上面的公式假设X 是离散的随机变量；一般化的公式可以同理得到。上面的推导仅仅用到了最基本的概率法则：第一步是全概率公式；第二步由可忽略性要求的条件独立性得到；第三步根据 $Z_i$ 将 $Y_i$ 替换成 $Y_i (1)$ 或者 $Y_i (0)$。这个公式的意义在于，最左边的平均因果作用 $\tau$ 的定义依赖于不可以完全被观测的潜在结果，最右边的量仅仅依赖于可以观测的变量
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +鲁宾还有很多其他关于因果推断的研究，这里就不再深入叙述；更多精彩的细节，可以在他的专著中找$到^8$。为了引入下一部分的内容，我需要对鲁宾的工作进行恰当的批判。上面介绍的理论有两个致命的问题。第一个问题是，处理 Zi 和结果Yi 之间的先后顺序是固定的，一前一后。但是， 很多实际问题可能存在Zi 和 Yi 同时产生，或者两者之间有动态关系的情况。鲁宾的这个简单模型，无法讨论这个问题。在计量经济学
缺公式环境 Zi，Yi

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +为了描述珀尔的因果图理论，我们需要一些图的基本语言。一组随机变量 $X = (X_1, \cdots , X_p)$ 形成一个 DAG ，每个节点对应着一个随机变量。我们用 $pa_j$ 表示和节点 $X_j$ 紧邻且处于箭头上游的变量集合（parent node），这个集合可能为空集。DAG 中变量的联合分布可以分解成
公式环境

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>一个 DAG 的例子
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +$$
下面公式环境请逐一核查

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +珀尔给出了一些更加有趣的结果：某些情况下，我们并不需要观测到所有的变量，也可以识别因果作用。下面用上面的 DAG 作为例子，解释他提出的“后门准则”（backdoor criterion）和“前门准则”（frontdoor criterion）。更一般的数学结果需要更多的术语和技术细节；感兴趣的读者可以参见珀尔的文章和专$著^{10}$。
脚注上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>珀尔和他的畅销书《为什么》，图片来自：https://momentmag.com/author-interview-judea- pearl/
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +珀尔的后门准则并没有给统计学家带来很大的惊喜，因为他给的公式在形式上并不是新的。但是，他的前门准则却让很多人吃惊。根据前门准则，我们仅仅需要观测 $(X_5, X_6, X_7)$ 的联合分布，就可以识别 $X_5$ 到 $X_7$ 的因果作用。直观上，$X_6$ 阻断了所有从 $X5$ 到 $X_7$ 的“前门路径”；另外，$X_5$ 到 $X_6$ 没有后门路径，$X_6$ 到 $X_7 的
$X_7 这个缺了一半公式环境，另外需要撇号保护

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +中国的文学作品，如屈原的《天问》和辛弃疾模仿而作的词《木兰花慢•可怜今夕月》，有一些对自然现象很感性的追问。佛教也有因果循环的理论。但是这些都没有和科学发生紧密联系。到了近代，中国学者受到了西方哲学的影响，也开始关注这个问题。比如，严复先生于1902 年翻译了约翰• 穆勒（John Stuart Mill）的名著《穆勒名$学》^{11}$，其中卷下第五章是“论因果”、第七章是“论观察试$验”^{
脚注上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>屈原的《天问》反映了中国古人对自然和历史的好奇心（图片来网络）
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +>学术界的“四世同堂”：耿直（右二）、学生郭建华（左二，东北师范大学副校长），学生的学生朱文圣（右一，东北师范大学数学与统计学院副院长），学生的学生的学生王鹏飞（左一，东北财经大学讲师）
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +因果推断需要关于混杂因素的假定，而判断某个变量是否是混杂因素，又需要关于因果关系的假定，这似乎有点循环论证。因此，确定什么是混杂因素是非常困难的。耿直探讨混杂因素的定义，提出了各种判断混杂因素的条件。其中一个结果是：如果不需要关于因果关系的假定，可以判断一个变量不是混杂因素，但不能确定一个变量是混杂因素。珀尔在《为什么》（The Book of Why）中写到，混杂因素问题的完整解决方案是因果革
脚注上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +> 替代指标悖论的图模型。此图表示一个随机化实验中，“吃药与否”是随机化的，所以和“未观测的变量”都独立，但是这些“未观测的变量”可能同时影响“替代指标”和“终点指标”。即使“吃药与否”对“终点指标”没有直接的影响，替代指标悖论也会发生：“吃药与否”对“替代指标”有正作用，“替代指标”对“终点指标”有正作用，但是“吃药与否”对“终点指标”的作用却是负的。这个悖论类似于前面提到的 Yule-Sim
图片标题

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +这项成果不仅有理论价值，而且对医学研究也有指导意义。有一本书《致命的药物》（Deadly Medicine）报告了一个真实的案例。医生的常识是，心律失常是猝死的危险因素，因此他们将纠正心律失常作为替代指标。一种新研制的药物能有效纠正心律失常，于是获得了美国食品药品监督管理局的批准。令人惊讶的是，该药物增加了数万人猝死，超过越南战争中美国士兵的死亡人数。这就是替代指标悖论的现实后果。几位杰出的统计
上标，唐纳德•鲁宾

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +如上面所述，珀尔关于因果作用可识别性的理论依赖一个完整已知的图模型。一个更有挑战性的问题是：如何从数据中学习未知的图模型？耿直提出了分解和局部学习的方法，化繁为简， 有针对性地构建图模型。在数据不能完全确定变量间因果图结构的情况下，他提出了一种实验设计的方法，干预最少的变量，将相关关系的图转变为因果关系的图。这对科学研究中的实验，有指导意义。这一系列文章发表在机器学习领域的顶级期刊 Journa
上标

2021-07-02 18:46 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +身处大数据时代，如何从海量数据中挖掘因果关系，也是一个非常有挑战性但是引人入胜的话题。由于研究深度学习（deep learning）而获得2018 年图灵奖的计算机科学家约书亚• 本希奥（Yoshua Bengio）最近转向因果推断的研究。他认为，机器学习和因果推断两种思想过去虽然独立发展，但是在未来会相互交织而产生新的成$果^{19}$。
上标

2021-07-02 22:49 UTC, StevenBoys commented
![dag2](https://user-images.githubusercontent.com/26518047/124334793-d8c28400-db5d-11eb-9d54-5473e26f29a2.png)

2021-07-03 21:56 UTC, yufree requested changes
辛苦博文！还有些细节需要参考丁鹏老师的修改版进行调整。

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> + - `$Z_i$`: 个体 i 吸烟与否的指示变量；
这里要断行才能出列表

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +`$$
此处公式不全，请参照原文

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +P(X) &= P(X_1) \cdot P(X_2) \cdot P(X_3|X_1,X_2) \cdot P(X_4|X_1,X_2,X_3) \\
这里要改成：

P(X) &= P(X_1) \cdot P(X_2) \cdot P(X_3|X_1,X_2) \cdot P(X_4|X_1) \\

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +P(X|do(X_5=1)) &= P(X_1) \cdot P(X_2) \cdot P(X_3|X_1,X_2) \cdot P(X_4|X_1,X_2,X_3) \\
这里要改成：
P(X|do(X_5=1)) &= P(X_1) \cdot P(X_2) \cdot P(X_3|X_1,X_2) \cdot P(X_4|X_1) \\

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +X_5 \leftarrow X_4 \leftarrow X_2 \rightarrow X_7,
此行删掉

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +X_5 \leftarrow X_1 \leftarrow X_3 \leftarrow X_4 \rightarrow X_7.
此行删掉

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +(c) `$X_5$` 到 `$X_7$` 的因果作用仅仅通过 `$X_6$` 产生，因此，`$X_5$` 到 `$X_7$` 的因果作用可以理解成 `$X_5$` 到 `$X_6$` 的因果作用和 `$X_6$` 到 `$X_7$` 的因果作用的“乘积” 。
(c) 这里显示效果有问题变成©了，可以考虑用`\`来调整

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +P(X) &= P(X_1) \cdot P(X_2) \cdot P(X_3|X_1,X_2) \cdot P(X_4|X_1,X_2,X_3) \\
这里公式也没有预览正确，考虑公式环境前空行

2021-07-03 21:56 UTC, yufree commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +那些指向 `$X_5$` 的、看似后门路径但是有“ `$\rightarrow \cdot \leftarrow$` ”这种结构的路径， 并不算成真正的后门路径。珀尔证明，仅仅用 `$(X_4, X_5, X_7)$` 的联合分布，我们就可以表示
这行改为：
指向 `$X_5$` 的、看似后门路径但是有“ `$\rightarrow \cdot \leftarrow$` ”这种结构的路径 `$(X_5 \leftarrow X_1 \rightarrow X_3 \leftarrow X_2 \rightarrow X_7$`， 并不算成真正的后门路径。珀尔证明，仅仅用 `$(X_4, X_5, X_7)$` 的联合分布，我们就可以表示

2021-07-06 01:29 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +人们常常问关于原因和结果的问题。比如，某人死于肺癌，是不是因为他常常吸烟导致的？比如，我感冒症状减轻了，是不是因为服用了维生素C片导致的？比如，大学教育是否能够提高收入水平？类似的问题，充满了我们的日常生活。
```suggestion
人们常常问关于原因和结果的问题。比如，某人死于肺癌，是不是因为他常常吸烟导致的？比如，我感冒症状减轻了，是不是因为服用了维生素 C 片导致的？比如，大学教育是否能够提高收入水平？类似的问题，充满了我们的日常生活。
```

2021-07-06 01:29 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +但是，这些看似直接了当的问题，却不容易回答。比如，有人吸烟，却没有得肺癌；有人不吸烟，却得了肺癌。比如，我可能仅仅喝白开水，感冒也会自己消失。比如，有人没有上大学，却做生意发了大财。当然，有点概率论常识的人很容易意识到，这些事件都带有随机性。从经验中，我们可能观察到吸烟的人更可能得肺癌；服用维生素C 的人，平均来说，自我感觉感冒恢复得更快；上过大学的人平均收入更高。但是，这些统计上的“相关关系”
```suggestion
但是，这些看似直接了当的问题，却不容易回答。比如，有人吸烟，却没有得肺癌；有人不吸烟，却得了肺癌。比如，我可能仅仅喝白开水，感冒也会自己消失。比如，有人没有上大学，却做生意发了大财。当然，有点概率论常识的人很容易意识到，这些事件都带有随机性。从经验中，我们可能观察到吸烟的人更可能得肺癌；服用维生素 C 的人，平均来说，自我感觉感冒恢复得更快；上过大学的人平均收入更高。但是，这些统计上的“相关关系”是否就是“因果关系”呢？
```

2021-07-06 01:33 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +以农业实验为例，考虑 n 块田作为实验的对象，实验者想检测两种肥料对于产量的影响。用i 表示第 i 块田，`$Y_i (1)$` 和 `$Y_i (0)$` 表示如果用肥料 1 和肥料 0 分别对应的第 i 块田的产量，那么 `$\tau_i = Y_i (1) − Y_i (0)$` 就是肥料 1 相对于肥料 0 对第 i 块田产量的因果作用。实验者随机地分配肥料1 或者肥料 0 到第 i 块
```suggestion
以农业实验为例，考虑 n 块田作为实验的对象，实验者想检测两种肥料对于产量的影响。用 i 表示第 i 块田，`$Y_i (1)$` 和 `$Y_i (0)$` 表示如果用肥料 1 和肥料 0 分别对应的第 i 块田的产量，那么 `$\tau_i = Y_i (1) − Y_i (0)$` 就是肥料 1 相对于肥料 0 对第 i 块田产量的因果作用。实验者随机地分配肥料1 或者肥料 0 到第 i 块田，所以最终我们要么观测到 `$Y_i (1)$`，要么观测到 `$Y_i (0)$`，不可能同时观测两者。显而易见，在这个模型下，因果推断的本质困难就是无法同时观测 `$Y_i (1)$` 和 `$Y_i (0)$`，也就无法直接观测到 `$\tau_i$`。观测单个的 `$\tau_i$` 太困难，退而求其次，我们可以考虑研究它的平均数：
```

2021-07-06 01:34 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +这个τ 通常被称为平均因果作用（average causal effect）。这可能是因果作用最简单的定义了。到此为止，内曼引入了一些数学记号来定义“因果作用”。也许读者会觉得这平平无奇，无非就是 `$Y_i (1)$` 和 `$Y_i (0)$` 。但是，这些记号将开启一扇窗，迎接新思想的曙光。
```suggestion
这个 `$\tau$` 通常被称为平均因果作用（average causal effect）。这可能是因果作用最简单的定义了。到此为止，内曼引入了一些数学记号来定义“因果作用”。也许读者会觉得这平平无奇，无非就是 `$Y_i (1)$` 和 `$Y_i (0)$` 。但是，这些记号将开启一扇窗，迎接新思想的曙光。
```

2021-07-06 01:35 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +潜在结果 `$Y_i (1)$` 和 `$Y_i (0)$`，以及平均因果作用 `$\tau$`，在某种意义上，都是假想的数字。仅有这些定义，还不能说明这个模型的现实意义。问题的关键是：我们能否根据观测到的数据推断 `$\tau$` ？内曼给出了肯定的回答。在随机化实验下，第 i 块田接受肥料 1 或者肥料 0是完全随机的。用 `$Z_i$` = 1 表示第 i 块田接受肥料 1，用 `$Z_i
```suggestion
潜在结果 `$Y_i (1)$` 和 `$Y_i (0)$`，以及平均因果作用 `$\tau$`，在某种意义上，都是假想的数字。仅有这些定义，还不能说明这个模型的现实意义。问题的关键是：我们能否根据观测到的数据推断 `$\tau$` ？内曼给出了肯定的回答。在随机化实验下，第 i 块田接受肥料 1 或者肥料 0 是完全随机的。用 `$Z_i$` = 1 表示第 i 块田接受肥料 1，用 `$Z_i$` = 0 表示第 i 块田接受肥料 0。随机化实验固定接受肥料 1 和肥料 0 的田的总数，分别是 `$n_1$` 和 `$n_0$`，对应的 `$(Z_1, \cdots, Z_n)$` 这个向量是 `$n_1$` 个1 和 `$n_0$` 个 0 的随机置换（random permutation）。如果第 i 块田接受了肥料 `$Z_i$`，那么我们观测到的产量就是
```

2021-07-06 01:38 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +\hat{\tau} = \frac{1}{n_1} \sum_{i:Z_i=i} Y_i - \frac{1}{n_0} \sum_{i:Z_i=0} Y_i .
```suggestion
\hat{\tau} = \frac{1}{n_1} \sum_{i:Z_i=1} Y_i - \frac{1}{n_0} \sum_{i:Z_i=0} Y_i .
```

2021-07-06 01:39 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +上面仅仅讨论了一个最简单的数学结构：两个组的随机化实验中的因果推断。现实中的随机化实验丰富多彩，如何在各种随机化实验中做因果推断取决于具体的实验设计方案。内曼本人于1935 年在英国皇家统计学会宣读的论文，讨论了随机区组设计（randomized block design）和拉丁方设计（Latin squares design）的因果推断，引发了包括罗纳德.费希尔（Ronald Fisher）
```suggestion
上面仅仅讨论了一个最简单的数学结构：两个组的随机化实验中的因果推断。现实中的随机化实验丰富多彩，如何在各种随机化实验中做因果推断取决于具体的实验设计方案。内曼本人于1935年在英国皇家统计学会宣读的论文，讨论了随机区组设计（randomized block design）和拉丁方设计（Latin squares design）的因果推断，引发了包括罗纳德.费希尔（Ronald Fisher） 在内的统计学家的激烈争论。同时期，费希尔对随机化实验进行了深入的研究，虽然他没有使用内曼潜在结果的记号，但是因果推断始终是他思考的对象。随后的几十年，随机对照实验（randomized controlled trial ；RCT）成为美国食品药品监督管理局批准新药的黄金标准。最近二十年，大量的随机化实验出现在社会科学中，用来研究复杂社会问题中的因果关系。比如，麻省理工学院和哈佛大学的三位经济学家，Abhijit Banerjee， Esther Duflo 和 Michael Kremer，因为用实验的方法研究发展经济学，获得了 2019 年的诺贝尔经济学奖。
```

2021-07-06 01:39 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +内曼生前对自己在统计假设检验方面的奠基性工作颇为自豪，认为那是统计学中“哥白尼式的革命”（Copernican Revolution）<sup>5</sup>。他并未预料他在因果推断的奠基性工作，也将产生深远的影响。这个影响则是由唐纳德• 鲁宾（Donald Rubin）开启的。
```suggestion
内曼生前对自己在统计假设检验方面的奠基性工作颇为自豪，认为那是统计学中“哥白尼式的革命”（Copernican Revolution）<sup>5</sup>。他并未预料他在因果推断的奠基性工作，也将产生深远的影响。这个影响则是由唐纳德•鲁宾（Donald Rubin）开启的。
```

2021-07-06 01:40 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +从直觉上，也许大家不会对随机化实验中的因果推断感到惊奇。毕竟随机化实验保证了两个组在平均意义下是相似的，那么他们之间的区别就可以归因于不同肥料对产量的因果作用。但是，现实的统计问题，很多数据收集并非源自随机化实验——这类研究通常被称为观察性研究（ observational study）。比如，如果要研究吸烟和肺癌的因果关系，基本的伦理不允许我们随机地让一部分人抽烟、让一部分人不抽烟。再如，研究
```suggestion
从直觉上，也许大家不会对随机化实验中的因果推断感到惊奇。毕竟随机化实验保证了两个组在平均意义下是相似的，那么他们之间的区别就可以归因于不同肥料对产量的因果作用。但是，现实的统计问题，很多数据收集并非源自随机化实验——这类研究通常被称为观察性研究（observational study）。比如，如果要研究吸烟和肺癌的因果关系，基本的伦理不允许我们随机地让一部分人抽烟、让一部分人不抽烟。再如，研究大学教育对收入的影响，我们不能随机地让一部分人上大学、让一部分人不上大学。很多流行病学和社会科学的问题，本质上一定是观察性研究，人们也迫切地想从这些观察性研究中获得关于因果关系的知识。
```

2021-07-06 01:41 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +鲁宾认为，观察性研究也对应着一个假想的随机化实验，因此内曼的潜在结果模型可以用来定义一般的因果作用。这里我们考虑一般的问题，不再局限于农田、肥料和产量。用 i 表示个体i，它的观测结果 `$Y_i$` 有两个潜在结果 `$Y_i (1)$` 和 `$Y_i (0)$`，分别对应两个处理水平，一般来说 1 被称为“处理”（treatment），而 0 被称为“对照”（control）。每个个体 i
```suggestion
鲁宾认为，观察性研究也对应着一个假想的随机化实验，因此内曼的潜在结果模型可以用来定义一般的因果作用。这里我们考虑一般的问题，不再局限于农田、肥料和产量。用 i 表示个体 i，它的观测结果 `$Y_i$` 有两个潜在结果 `$Y_i (1)$` 和 `$Y_i (0)$`，分别对应两个处理水平，一般来说 1 被称为“处理”（treatment），而 0 被称为“对照”（control）。每个个体 i 有一个二值的处理水平 `$Z_i$` 和一些处理前的协变量 `$X_i$`。一个具体的例子是：
```

2021-07-06 01:41 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +鲁宾给了一个关于 τ 的因果推断的充分条件：给定协变量 `$X_i$`，潜在结果`$(Y_i (1), Y_i (0) )$` 和 处理变量 `$Z_i$` 条件独立。
```suggestion
鲁宾给了一个关于 `$\tau$` 的因果推断的充分条件：给定协变量 `$X_i$`，潜在结果 `$(Y_i (1), Y_i (0) )$` 和 处理变量 `$Z_i$` 条件独立。
```

2021-07-06 01:42 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +为了简单起见，上面的公式假设X 是离散的随机变量；一般化的公式可以同理得到。上面的推导仅仅用到了最基本的概率法则：第一步是全概率公式；第二步由可忽略性要求的条件独立性得到；第三步根据 `$Z_i$` 将 `$Y_i$` 替换成 `$Y_i (1)$` 或者 `$Y_i (0)$`。这个公式的意义在于，最左边的平均因果作用 `$\tau$` 的定义依赖于不可以完全被观测的潜在结果，最右边的量仅仅依
```suggestion
为了简单起见，上面的公式假设 X 是离散的随机变量；一般化的公式可以同理得到。上面的推导仅仅用到了最基本的概率法则：第一步是全概率公式；第二步由可忽略性要求的条件独立性得到；第三步根据 `$Z_i$` 将 `$Y_i$` 替换成 `$Y_i (1)$` 或者 `$Y_i (0)$`。这个公式的意义在于，最左边的平均因果作用 `$\tau$` 的定义依赖于不可以完全被观测的潜在结果，最右边的量仅仅依赖于可以观测的变量 `$(Z_i, X_i, Y_i)$` 的联合分布。用一个技术性的术语来描述上面的公式，就是，基于观测数据，平均因果作用是可识别的（identifiable）。直观上，我们可以用观测数据构造平均因果作用的估计量。比如，我们可以拟合 `$Y_i$` 关于 `$(Z_i, X_i)$` 的统计模型，则可以进一步根据上面的公式估计 `$\tau$`.
```

2021-07-06 01:43 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +Rosenbaum 和鲁宾的这篇文章是Biometrika 这个杂志创刊以来引用率最高的两篇文章之一<sup>7</sup>。在它发表后的三十多年里，引起了很多理论统计学家和应用统计学家的兴趣，他们提出了很多推广的、更加精致的理论和方法，这些理论和方法被用在流行病学、经济学、政治科学等诸多学科的研究中。
```suggestion
Rosenbaum 和鲁宾的这篇文章是 Biometrika 这个杂志创刊以来引用率最高的两篇文章之一<sup>7</sup>。在它发表后的三十多年里，引起了很多理论统计学家和应用统计学家的兴趣，他们提出了很多推广的、更加精致的理论和方法，这些理论和方法被用在流行病学、经济学、政治科学等诸多学科的研究中。
```

2021-07-06 01:44 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +鲁宾还有很多其他关于因果推断的研究，这里就不再深入叙述；更多精彩的细节，可以在他的专著中找到<sup>8</sup>。为了引入下一部分的内容，我需要对鲁宾的工作进行恰当的批判。上面介绍的理论有两个致命的问题。第一个问题是，处理 Zi 和结果Yi 之间的先后顺序是固定的，一前一后。但是， 很多实际问题可能存在Zi 和 Yi 同时产生，或者两者之间有动态关系的情况。鲁宾的这个简单模型，无法讨论这个问
```suggestion
鲁宾还有很多其他关于因果推断的研究，这里就不再深入叙述；更多精彩的细节，可以在他的专著中找到<sup>8</sup>。为了引入下一部分的内容，我需要对鲁宾的工作进行恰当的批判。上面介绍的理论有两个致命的问题。第一个问题是，处理 `$Z_i$` 和结果 `$Y_i$` 之间的先后顺序是固定的，一前一后。但是， 很多实际问题可能存在 `$Z_i$` 和 `$Y_i$` 同时产生，或者两者之间有动态关系的情况。鲁宾的这个简单模型，无法讨论这个问题。在计量经济学中，这被称为“联立方程模型”（simultaneous equation model）。第二个问题是，可忽略性假定的合理性如何判定？这个条件独立性不可能被观测数据验证，那么我们如何能相信由它导出的数学结果呢？费希尔曾经质疑吸烟导致肺癌的研究，他认为，可能存在一个基因，它既导致人更容易吸烟，也导致人更容易得肺癌，所以我们看到的吸烟和肺癌之前的相关性可能是虚假的因果作用。如果我们遗漏掉了关于这个基因的信息，那么鲁宾要求的可忽略性就不成立。
```

2021-07-06 01:44 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +用上面的图，如何思考因果关系的问题呢？珀尔引入了do 算子，表示干预某个随机变量到某个值，这类似我们在实验中控制某个变量。我先给一般的公式，再给具体的例子。一般地，
```suggestion
用上面的图，如何思考因果关系的问题呢？珀尔引入了 do 算子，表示干预某个随机变量到某个值，这类似我们在实验中控制某个变量。我先给一般的公式，再给具体的例子。一般地，
```

2021-07-06 01:45 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +从这个联合分布积分，我们可以得到边缘分布 `$P (X_7 = x_7 | do(X_5 = 1))$`。类似可得 `$P (X7 = x7 | do(X5 = 0))$`。进一步可以计算 `$X_5$` 对 `$X_7$` 的平均因果作用。但是这个例子的趣味性还不够，因为上面的计算公式要求我们观测到所有变量的联合分布。
```suggestion
从这个联合分布积分，我们可以得到边缘分布 `$P (X_7 = x_7 | do(X_5 = 1))$`。类似可得 `$P (X_7 = x_7 | do(X_5 = 0))$`。进一步可以计算 `$X_5$` 对 `$X_7$` 的平均因果作用。但是这个例子的趣味性还不够，因为上面的计算公式要求我们观测到所有变量的联合分布。
```

2021-07-06 01:46 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +指向 $X_5$ 的、看似后门路径但是有“ $\rightarrow \cdot \leftarrow$ ”这种结构的路径 $(X_5 \leftarrow X_1 \rightarrow X_3 \leftarrow X_2 \rightarrow X_7$， 并不算成真正的后门路径。珀尔证明，仅仅用 $(X_4, X_5, X_7)$ 的联合分布，我们就可以表示
```suggestion
指向 `$X_5$` 的、看似后门路径但是有“ `$\rightarrow \cdot \leftarrow$` ”这种结构的路径 `$(X_5 \leftarrow X_1 \rightarrow X_3 \leftarrow X_2 \rightarrow X_7$`， 并不算成真正的后门路径。珀尔证明，仅仅用 `$(X_4, X_5, X_7)$` 的联合分布，我们就可以表示
```

2021-07-06 01:46 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +珀尔的后门准则并没有给统计学家带来很大的惊喜，因为他给的公式在形式上并不是新的。但是，他的前门准则却让很多人吃惊。根据前门准则，我们仅仅需要观测 `$(X_5, X_6, X_7)$` 的联合分布，就可以识别 `$X_5$` 到 `$X_7$` 的因果作用。直观上，`$X_6$` 阻断了所有从 `$X5$` 到 `$X_7$` 的“前门路径”；另外，`$X_5$` 到 `$X_6$` 没有后门路
```suggestion
珀尔的后门准则并没有给统计学家带来很大的惊喜，因为他给的公式在形式上并不是新的。但是，他的前门准则却让很多人吃惊。根据前门准则，我们仅仅需要观测 `$(X_5, X_6, X_7)$` 的联合分布，就可以识别 `$X_5$` 到 `$X_7$` 的因果作用。直观上，`$X_6$` 阻断了所有从 `$X_5$` 到 `$X_7$` 的“前门路径”；另外，`$X_5$` 到 `$X_6$` 没有后门路径，`$X_6$` 到 `$X_7$` 的后门路径都被 `$X_5$` 阻断了。在这些约束下，珀尔证明了下面的前门准则公式：
```

2021-07-06 01:47 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +珀尔在他1995 年的Biometrika 文章中给出了上面的和其他更一般的结果。他的文章引发了众多统计学家的讨论，当时大部分统计学家都保持怀疑甚至否定的态度，因为他的理论要求一个完全已知的图，这对大部分应用统计问题来说，是不切实际的。但是，珀尔的因果图，作为理论工具，对大家思考因果关系有很大的帮助。即使它不能直接用于数据分析，不少统计学家也认为他的理论有助于指导数据分析。珀尔由于这项工作于 2
```suggestion
珀尔在他 1995 年的 Biometrika 文章中给出了上面的和其他更一般的结果。他的文章引发了众多统计学家的讨论，当时大部分统计学家都保持怀疑甚至否定的态度，因为他的理论要求一个完全已知的图，这对大部分应用统计问题来说，是不切实际的。但是，珀尔的因果图，作为理论工具，对大家思考因果关系有很大的帮助。即使它不能直接用于数据分析，不少统计学家也认为他的理论有助于指导数据分析。珀尔由于这项工作于 2011 年获得了计算机科学的最高奖——图灵奖。
```

2021-07-06 01:47 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +统计学里有个很有名的Yule-Simpson 悖论：由于忽略某个变量，使得两个变量间的相关关系出现逆反现象。例如，某药对男性有效，对女性也有效，但是合并男和女后，发现该药对总体无效。这个悖论与前面休谟的质疑有些联系，即，从经验归纳不出因果关系。在这个悖论中被忽略的那个变量，被称为混杂因素（confounder）。它是因果推断的关键。前面鲁宾的可忽略性也被称为无混杂性，即排除了未观测的混杂因素，他
```suggestion
统计学里有个很有名的 Yule-Simpson 悖论：由于忽略某个变量，使得两个变量间的相关关系出现逆反现象。例如，某药对男性有效，对女性也有效，但是合并男和女后，发现该药对总体无效。这个悖论与前面休谟的质疑有些联系，即，从经验归纳不出因果关系。在这个悖论中被忽略的那个变量，被称为混杂因素（confounder）。它是因果推断的关键。前面鲁宾的可忽略性也被称为无混杂性，即排除了未观测的混杂因素，他的理论才成立。
```

2021-07-06 01:48 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +身处大数据时代，如何从海量数据中挖掘因果关系，也是一个非常有挑战性但是引人入胜的话题。由于研究深度学习（deep learning）而获得2018 年图灵奖的计算机科学家约书亚• 本希奥（Yoshua Bengio）最近转向因果推断的研究。他认为，机器学习和因果推断两种思想过去虽然独立发展，但是在未来会相互交织而产生新的成果<sup>19</sup>。
```suggestion
身处大数据时代，如何从海量数据中挖掘因果关系，也是一个非常有挑战性但是引人入胜的话题。由于研究深度学习（deep learning）而获得 2018 年图灵奖的计算机科学家约书亚• 本希奥（Yoshua Bengio）最近转向因果推断的研究。他认为，机器学习和因果推断两种思想过去虽然独立发展，但是在未来会相互交织而产生新的成果<sup>19</sup>。
```

2021-07-06 01:48 UTC, Ryanna-github commented on content/post/2021-06-27-causal-inference-modern-statistics-leap.md
> +因果推断的研究，对规范我国药物批准和政策评估，也大有帮助。比如，前面提到的Prentice 和鲁宾，都常常为美国食品药品监督管理局做咨询，解决他们在评估药效方面遇到的困难。我国的生物医药行业在未来有很大的腾飞空间，因果推断的学者们将发挥他们的巨大作用。再如，美国顶级高校的公共政策学院或者政府学院，都有研究因果推断的专家，他们研究公共政策对社会福利的影响，对于优化社会资源，起着重要作用。研究因果推
```suggestion
因果推断的研究，对规范我国药物批准和政策评估，也大有帮助。比如，前面提到的 Prentice 和鲁宾，都常常为美国食品药品监督管理局做咨询，解决他们在评估药效方面遇到的困难。我国的生物医药行业在未来有很大的腾飞空间，因果推断的学者们将发挥他们的巨大作用。再如，美国顶级高校的公共政策学院或者政府学院，都有研究因果推断的专家，他们研究公共政策对社会福利的影响，对于优化社会资源，起着重要作用。研究因果推断的学者，以后也应该走出象牙塔，承担社会责任。
```

2021-07-06 17:24 UTC, yufree commented
感谢博文 @StevenBoys 与任焱 @Ryanna-github ！目前丁鹏老师那边已经没有进一步修改意见，请 @Ryanna-github 安排人进行微信端排版，请 @Perfectizer 准备论坛帖子，计划本周内推送这篇文章。

2021-07-06 17:26 UTC, yufree approved these changes

2021-07-09 13:40 UTC, merged